const firebaseConfig = {
  apiKey: "AIzaSyDm3NcIjnLestNntscRXbeChvEwwqxkg8E",
  authDomain: "zoprint-c4891.firebaseapp.com",
  databaseURL: "https://zoprint-c4891-default-rtdb.firebaseio.com",
  projectId: "zoprint-c4891",
  storageBucket: "zoprint-c4891.firebasestorage.app",
  messagingSenderId: "944996490044",
  appId: "1:944996490044:web:ccfc3cfacc4acd04d45c39",
  measurementId: "G-CVWYCKMN01"
};
firebase.initializeApp(firebaseConfig);const auth=firebase.auth(),db=firebase.firestore();
let adminUser=null,apps=[],requests=[],activity=[];let unsubApps=null,unsubReq=null;
const $=id=>document.getElementById(id); const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=v=>{if(!v)return '—';const d=v.toDate? v.toDate():new Date(v);return isNaN(d)?'—':d.toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});};
const norm=v=>String(v||'').toLowerCase(); const statusBadge=v=>`<span class="badge ${norm(v).replace(/[^a-z]+/g,'-')}">${esc(v||'pending')}</span>`;
function toast(m,type='ok'){const t=$('toast');t.textContent=m;t.className='show '+type;setTimeout(()=>t.className='',2600)}
function openModal(html){$('modalBody').innerHTML=html;$('modal').classList.remove('hidden')}function closeModal(){$('modal').classList.add('hidden')}
window.closeModal=closeModal;
function logAction(action,detail=''){if(!adminUser)return;db.collection('adminActivity').add({adminUid:adminUser.uid,adminEmail:adminUser.email,action,detail,createdAt:firebase.firestore.FieldValue.serverTimestamp()}).catch(()=>{})}
async function ensureAdmin(user){const s=await db.collection('users').doc(user.uid).get();const d=s.exists?s.data():{};return d.role==='admin'||d.isAdmin===true||d.admin===true}
auth.onAuthStateChanged(async user=>{if(!user){$('loginView').classList.remove('hidden');$('app').classList.add('hidden');return}try{if(!(await ensureAdmin(user))){await auth.signOut();$('loginMsg').textContent='Access denied: admin account required.';return}adminUser=user;$('loginView').classList.add('hidden');$('app').classList.remove('hidden');$('adminName').textContent=user.displayName||'Administrator';$('adminEmail').textContent=user.email||'';$('adminAvatar').textContent=(user.displayName||user.email||'A').charAt(0).toUpperCase();$('settingsEmail').textContent=user.email||'—';startLive();loadActivity();loadSettings()}catch(e){await auth.signOut();$('loginMsg').textContent='Could not verify admin access.'}});
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginMsg').textContent='';try{await auth.signInWithEmailAndPassword($('email').value.trim(),$('password').value)}catch(e){$('loginMsg').textContent=e.message.replace('Firebase:','').trim()}});$('logoutBtn').onclick=()=>auth.signOut();$('refreshBtn').onclick=()=>{renderAll();loadActivity();toast('Refreshed')};
function startLive(){unsubApps?.();unsubReq?.();unsubApps=db.collection('applications').orderBy('createdAt','desc').onSnapshot(s=>{apps=s.docs.map(d=>({id:d.id,...d.data()}));renderAll();$('lastUpdated').textContent='Updated '+new Date().toLocaleTimeString('en-IN')},e=>toast('Applications load error: '+e.message,'error'));unsubReq=db.collection('customerPaymentRequests').orderBy('createdAt','desc').onSnapshot(s=>{requests=s.docs.map(d=>({id:d.id,...d.data()}));renderAll()},e=>toast('Payment requests error: '+e.message,'error'))}
function renderAll(){renderStats();renderRecent();renderApps();renderPayments();renderRequests();}
function renderStats(){const pending=apps.filter(a=>norm(a.status)==='pending').length,under=apps.filter(a=>norm(a.status)==='under process').length,approved=apps.filter(a=>norm(a.status)==='approved').length,rejected=apps.filter(a=>norm(a.status)==='rejected').length,paid=apps.filter(a=>norm(a.paymentStatus)==='paid').length,verify=apps.filter(a=>norm(a.paymentStatus)==='verification_pending').length;const amount=apps.filter(a=>norm(a.paymentStatus)==='paid').reduce((n,a)=>n+Number(a.paymentAmount||190),0);$('statsCards').innerHTML=[['Total Applications',apps.length,'fa-folder-open'],['Pending',pending,'fa-hourglass-half'],['Under Process',under,'fa-arrows-rotate'],['Approved',approved,'fa-circle-check'],['Rejected',rejected,'fa-circle-xmark'],['Payment Pending',verify,'fa-money-bill-transfer'],['Paid Applications',paid,'fa-circle-check'],['Verified Amount','₹'+amount.toLocaleString('en-IN'),'fa-indian-rupee-sign']].map(x=>`<div class="stat"><i class="fa-solid ${x[2]}"></i><div><span>${x[0]}</span><b>${x[1]}</b></div></div>`).join('')}
function renderRecent(){const rows=apps.slice(0,7).map(a=>`<tr><td><b>${esc(a.ackNo)}</b><small>${esc(a.applicationType||'New PAN')}</small></td><td>${esc(a.name||'—')}</td><td>${statusBadge(a.status)}</td><td>${statusBadge(a.paymentStatus||'pending')}</td><td><button class="mini" onclick="viewApp('${a.id}')">View</button> <button class="mini primary" onclick="editApplication('${a.id}')"><i class="fa-solid fa-pen"></i> Edit</button></td></tr>`).join('');$('recentApps').innerHTML=table(['ACK / Type','Applicant','Status','Payment',''],rows);$('recentPayments').innerHTML=apps.filter(a=>norm(a.paymentStatus)==='verification_pending').slice(0,6).map(a=>`<div class="pay-row"><div><b>${esc(a.ackNo)}</b><span>${esc(a.name||'—')} • ₹${Number(a.paymentAmount||190)}</span></div><button class="mini primary" onclick="viewApp('${a.id}')">Review</button></div>`).join('')||'<div class="empty">No payments awaiting verification.</div>'}
function table(head,rows){return `<table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||'<tr><td colspan="9" class="empty">No records found.</td></tr>'}</tbody></table>`}
function renderApps(){const q=norm($('appSearch').value),st=$('appStatus').value,p=$('appPay').value,ty=$('appType').value;const list=apps.filter(a=>(!q||[a.ackNo,a.name,a.phone,a.panNumber,a.email].some(v=>norm(v).includes(q)))&&(st==='all'||norm(a.status)===norm(st))&&(p==='all'||norm(a.paymentStatus)===norm(p))&&(ty==='all'||(a.applicationType||'New PAN')===ty));$('applicationsTable').innerHTML=table(['ACK / Date','Applicant','Mobile','Type','Status','Payment','Amount','Action'],list.map(a=>`<tr><td><b>${esc(a.ackNo)}</b><small>${fmtDate(a.createdAt)}</small></td><td>${esc(a.name||'—')}</td><td>${esc(a.phone||'—')}</td><td>${esc(a.applicationType||'New PAN')}</td><td>${statusBadge(a.status)}</td><td>${statusBadge(a.paymentStatus||'pending')}</td><td>₹${Number(a.paymentAmount||190).toLocaleString('en-IN')}</td><td><button class="mini" onclick="viewApp('${a.id}')">Open</button> <button class="mini primary" onclick="editApplication('${a.id}')"><i class="fa-solid fa-pen"></i> Edit</button></td></tr>`).join(''))}
function renderPayments(){const q=norm($('paySearch').value),f=$('payFilter').value;const list=apps.filter(a=>(f==='all'||norm(a.paymentStatus)===norm(f))&&(!q||[a.ackNo,a.name,a.paymentUtr,a.utr].some(v=>norm(v).includes(q))));$('paymentsTable').innerHTML=table(['ACK','Applicant','Amount','UTR','Payment','Submitted','Action'],list.map(a=>`<tr><td><b>${esc(a.ackNo)}</b></td><td>${esc(a.name||'—')}</td><td>₹${Number(a.paymentAmount||190)}</td><td>${esc(a.paymentUtr||a.utr||'—')}</td><td>${statusBadge(a.paymentStatus||'pending')}</td><td>${fmtDate(a.paymentSubmittedAt||a.customerSubmittedAt)}</td><td><button class="mini primary" onclick="viewApp('${a.id}')">Review</button></td></tr>`).join(''))}
function renderRequests(){const q=norm($('reqSearch').value),f=$('reqFilter').value;const list=requests.filter(r=>(f==='all'||norm(r.status)===norm(f))&&(!q||[r.ackNo,r.name,r.phone,r.id,r.utr].some(v=>norm(v).includes(q))));$('requestsTable').innerHTML=table(['Request','ACK','Customer','Amount','UTR','Status','Created','Action'],list.map(r=>`<tr><td><b>${esc(r.id.slice(0,10))}</b></td><td>${esc(r.ackNo)}</td><td>${esc(r.name||'—')}</td><td>₹${Number(r.amount||190)}</td><td>${esc(r.utr||'—')}</td><td>${statusBadge(r.status)}</td><td>${fmtDate(r.createdAt)}</td><td><button class="mini primary" onclick="viewRequest('${r.id}')">Open</button></td></tr>`).join(''))}
['appSearch','appStatus','appPay','appType','paySearch','payFilter','reqSearch','reqFilter'].forEach(id=>$(id).addEventListener('input',renderAll));
['appStatus','appPay','appType','payFilter','reqFilter'].forEach(id=>$(id).addEventListener('change',renderAll));
async function viewApp(id){const a=apps.find(x=>x.id===id);if(!a)return;logAction('Viewed application',a.ackNo);openModal(`<div class="detail-head"><div><span class="eyebrow">${esc(a.applicationType||'New PAN')}</span><h2>${esc(a.name||'Application')}</h2><p>ACK: <b>${esc(a.ackNo)}</b> • ${fmtDate(a.createdAt)}</p></div><div>${statusBadge(a.status)} ${statusBadge(a.paymentStatus||'pending')}</div></div><div class="detail-actions"><button class="primary" onclick="setAppStatus('${id}','under process')">Under Process</button><button class="success" onclick="setAppStatus('${id}','approved')">Approve</button><button class="danger" onclick="setAppStatus('${id}','rejected')">Reject</button><button onclick="openDocs('${id}')">Documents</button><button onclick="whatsappApp('${id}')">WhatsApp</button></div><div class="detail-grid">${field('ACK Number',a.ackNo)}${field('Applicant',a.name)}${field('Mobile',a.phone)}${field('Email',a.email)}${field('PAN',a.panNumber||'—')}${field('DOB',a.dob)}${field('Gender',a.gender)}${field("Father's Name (First • Middle • Last)",[a.fatherFirstName,a.fatherMiddleName,a.fatherlastName||a.fatherLastName].filter(Boolean).join(' ')||a.father||a.fatherName||'—')}${field("Mother's Name (First • Middle • Last)",[a.motherFirstName,a.motherMiddleName,a.motherlastName||a.motherLastName].filter(Boolean).join(' ')||a.mother||a.motherName||'—')}${field('Address',[a.flatNo,a.villageCity,a.postOffice,a.subDivision,a.district,a.state,a.pinCode].filter(Boolean).join(', '))}${field('Payment Amount','₹'+Number(a.paymentAmount||190))}${field('UTR',a.paymentUtr||a.utr||'—')}${field('Created',fmtDate(a.createdAt))}</div>${a.correctionFields?`<div class="subpanel"><h3>Correction Fields</h3><p>${esc(Array.isArray(a.correctionFields)?a.correctionFields.join(', '):a.correctionFields)}</p></div>`:''}<div class="timeline"><h3>Application Timeline</h3>${timeline(a)}</div>`)}
function field(k,v){return `<div class="field"><span>${esc(k)}</span><b>${esc(v||'—')}</b></div>`}function timeline(a){const st=norm(a.status);const paid=norm(a.paymentStatus)==='paid';return [['Application Submitted',true],['Payment Verified',paid],['Under Process',['under process','approved'].includes(st)],['Approved',st==='approved'],['Rejected',st==='rejected']].map(x=>`<div class="tl ${x[1]?'done':''}"><i class="fa-solid ${x[1]?'fa-check':'fa-circle'}"></i><span>${x[0]}</span></div>`).join('')}
async function setAppStatus(id,status){try{await db.collection('applications').doc(id).update({status,statusUpdatedAt:firebase.firestore.FieldValue.serverTimestamp(),statusUpdatedBy:adminUser.email});logAction('Changed application status',`${id} → ${status}`);toast('Status updated');closeModal()}catch(e){toast(e.message,'error')}}
async function verifyPayment(id,ok=true){const a=apps.find(x=>x.id===id);if(!a)return;try{await db.collection('applications').doc(id).update({paymentStatus:ok?'paid':'rejected',paymentVerifiedAt:firebase.firestore.FieldValue.serverTimestamp(),paymentVerifiedBy:adminUser.email});const req=requests.find(r=>r.applicationId===id||r.ackNo===a.ackNo);if(req)await db.collection('customerPaymentRequests').doc(req.id).update({status:ok?'paid':'rejected',paymentStatus:ok?'paid':'rejected',verifiedAt:firebase.firestore.FieldValue.serverTimestamp(),verifiedBy:adminUser.email});logAction(ok?'Verified payment':'Rejected payment',a.ackNo);toast(ok?'Payment verified':'Payment rejected');closeModal()}catch(e){toast(e.message,'error')}}
function viewRequest(id){const r=requests.find(x=>x.id===id);if(!r)return;const app=apps.find(a=>a.id===r.applicationId||a.ackNo===r.ackNo);openModal(`<div class="detail-head"><div><span class="eyebrow">Payment Request</span><h2>${esc(r.name||'Customer')}</h2><p>ACK: <b>${esc(r.ackNo)}</b></p></div>${statusBadge(r.status)}</div><div class="detail-grid">${field('Request ID',r.id)}${field('Amount','₹'+Number(r.amount||190))}${field('Mobile',r.phone)}${field('Application',r.applicationType)}${field('UTR',r.utr||'—')}${field('Created',fmtDate(r.createdAt))}</div><div class="detail-actions"><button class="success" onclick="${app?`verifyPayment('${app.id}',true)`:''}">Verify Payment</button><button class="danger" onclick="${app?`verifyPayment('${app.id}',false)`:''}">Reject Payment</button>${r.paymentScreenshot?`<a class="button" href="${esc(r.paymentScreenshot)}" target="_blank">Payment Proof</a>`:''}</div>`)}
function openDocs(id){const a=apps.find(x=>x.id===id);if(!a)return;const docs=[['Photo',a.photo],['Signature',a.signature],['Aadhaar Front',a.aadhaarFront],['Aadhaar Back',a.aadhaarBack],['DOB Proof',a.dobProof],['Guardian Front',a.guardianFront],['Guardian Back',a.guardianBack]].filter(d=>d[1]);openModal(`<div class="detail-head"><div><span class="eyebrow">Document Center</span><h2>${esc(a.name||'Application')}</h2><p>ACK: ${esc(a.ackNo)} • ${esc(a.applicationType||'PAN')}</p></div></div><div class="doc-grid">${docs.map(d=>`<div class="doc-card"><div class="doc-preview"><img src="${esc(d[1])}" alt="${esc(d[0])}"></div><b>${esc(d[0])}</b><div class="doc-actions"><a href="${esc(d[1])}" target="_blank">Open</a><button onclick="downloadDocJpg('${esc(d[1])}','${esc(a.ackNo+'_'+d[0].replace(/\s+/g,'_'))}')">Download JPG</button></div></div>`).join('')||'<div class="empty">No documents found.</div>'}</div>`)}
function whatsappApp(id){const a=apps.find(x=>x.id===id);if(!a)return;const msg=`TECH SOURCE PAN Update%0AACK: ${a.ackNo}%0AName: ${a.name||''}%0AApplication: ${a.applicationType||'New PAN'}%0AStatus: ${a.status||'pending'}%0APayment: ${a.paymentStatus||'pending'}`;window.open('https://wa.me/'+String(a.phone||'').replace(/\D/g,'')+'?text='+msg,'_blank');logAction('Opened WhatsApp',a.ackNo)}
window.viewApp=viewApp;window.viewRequest=viewRequest;window.verifyPayment=verifyPayment;window.setAppStatus=setAppStatus;window.openDocs=openDocs;window.whatsappApp=whatsappApp;

async function loadActivity(){if(!adminUser)return;try{const s=await db.collection('adminActivity').orderBy('createdAt','desc').limit(100).get();activity=s.docs.map(d=>d.data());$('activityTable').innerHTML=table(['Time','Admin','Action','Detail'],activity.map(x=>`<tr><td>${fmtDate(x.createdAt)}</td><td>${esc(x.adminEmail)}</td><td>${esc(x.action)}</td><td>${esc(x.detail)}</td></tr>`).join(''))}catch(e){$('activityTable').innerHTML='<div class="empty">Activity log unavailable until Firestore rules/index are configured.</div>'}}
function loadSettings(){const raw=localStorage.getItem('ts_pan_admin_settings');if(!raw)return;try{const s=JSON.parse(raw);$('setBusiness').value=s.business||'TECH SOURCE';$('setUpi').value=s.upi||'9661905351-3@axl';$('setFee').value=s.fee||190;$('setWhatsapp').value=s.whatsapp||'9661905351'}catch{}}
$('saveSettings').onclick=()=>{localStorage.setItem('ts_pan_admin_settings',JSON.stringify({business:$('setBusiness').value,upi:$('setUpi').value,fee:$('setFee').value,whatsapp:$('setWhatsapp').value}));$('settingsMsg').textContent='Saved on this admin browser. Firebase application fee remains controlled by the application code.';toast('Settings saved')};
document.querySelectorAll('[data-section]').forEach(btn=>btn.onclick=()=>go(btn.dataset.section));document.querySelectorAll('[data-go]').forEach(btn=>btn.onclick=()=>go(btn.dataset.go));function go(id){document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('[data-section]').forEach(b=>b.classList.toggle('active',b.dataset.section===id));$('pageTitle').textContent=id==='requests'?'Payment Requests':id==='deleteApplications'?'Delete Applications':id.charAt(0).toUpperCase()+id.slice(1);document.querySelector('.sidebar').classList.remove('open');window.scrollTo(0,0)}$('menuBtn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');

/* ================= APPROVAL + DOCUMENT CENTER UPGRADE ================= */
async function adminCloudinaryUpload(file, folder='pan_final'){
  const url='https://api.cloudinary.com/v1_1/dsnuatuc8/image/upload'; const fd=new FormData(); fd.append('file',file); fd.append('upload_preset','ml_default'); fd.append('folder',folder);
  const res=await fetch(url,{method:'POST',body:fd}); const d=await res.json(); if(!res.ok||!d.secure_url) throw new Error(d.error?.message||'Cloudinary upload failed'); return d.secure_url.replace('/upload/','/upload/f_auto,q_auto/');
}

function openApproveUpload(id){const a=apps.find(x=>x.id===id);if(!a)return;openModal(`<div class="approval-upload"><div class="detail-head"><div><span class="eyebrow">FINAL PAN CARD</span><h2>Approve: ${esc(a.name||'Application')}</h2><p>ACK: <b>${esc(a.ackNo)}</b></p></div></div><div class="upload-drop"><i class="fa fa-id-card" style="font-size:30px"></i><p>Final PAN card JPG upload karein. Only JPG, JPEG, PNG or WEBP image is allowed.</p><input id="finalPanFile" type="file" accept="image/jpeg,image/png,image/webp"></div><div class="upload-progress"><span id="finalPanProgress"></span></div><p id="finalPanMsg" class="message"></p><div class="detail-actions"><button onclick="closeModal()">Cancel</button><button class="success" id="finalPanApproveBtn" onclick="uploadFinalPanAndApprove('${id}')">Upload & Approve</button></div></div>`)}
async function uploadFinalPanAndApprove(id){const input=$('finalPanFile'),msg=$('finalPanMsg'),bar=$('finalPanProgress'),btn=$('finalPanApproveBtn');const file=input?.files?.[0];if(!file){msg.textContent='Final PAN card file select karein.';return}btn.disabled=true;msg.textContent='Preparing final PAN…';try{let jpg=file;if(!file.type.startsWith('image/'))throw new Error('Only image files are supported.');bar.style.width='35%';msg.textContent='Uploading final PAN…';const url=await adminCloudinaryUpload(jpg,'pan_final_cards');bar.style.width='85%';await db.collection('applications').doc(id).update({status:'approved',documentUrl:url,panCardUrl:url,finalPanCardUploadedAt:firebase.firestore.FieldValue.serverTimestamp(),statusUpdatedAt:firebase.firestore.FieldValue.serverTimestamp(),statusUpdatedBy:adminUser.email});logAction('Approved application + uploaded PAN card',apps.find(x=>x.id===id)?.ackNo||id);bar.style.width='100%';msg.style.color='#15803d';msg.textContent='Approved. PAN card ready for download.';setTimeout(closeModal,700)}catch(e){msg.style.color='#dc2626';msg.textContent=e.message||String(e);btn.disabled=false}}
window.openApproveUpload=openApproveUpload;window.uploadFinalPanAndApprove=uploadFinalPanAndApprove;

async function downloadDocJpg(url,name){try{const r=await fetch(url);const b=await r.blob();if(!b.type.startsWith('image/'))throw new Error('Only image documents can be downloaded.');const img=new Image();img.crossOrigin='anonymous';const u=URL.createObjectURL(b);await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=u});const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext('2d').drawImage(img,0,0);const blob=await new Promise(x=>c.toBlob(x,'image/jpeg',.94));URL.revokeObjectURL(u);const out=URL.createObjectURL(blob);const a=document.createElement('a');a.href=out;a.download=name+'.jpg';a.click();setTimeout(()=>URL.revokeObjectURL(out),1000)}catch(e){toast('JPG download failed: '+(e.message||e),'error')}}
window.downloadDocJpg=downloadDocJpg;

// Override status action so Approve always requires final PAN upload.
const _oldSetAppStatus=setAppStatus; setAppStatus=async function(id,status){if(status==='approved'){openApproveUpload(id);return}_oldSetAppStatus(id,status)};window.setAppStatus=setAppStatus;

// Enforce owner-only payment-link creation in the admin preview as well as duplicate reuse in user flow.
const _oldViewRequest=viewRequest;
viewRequest=function(id){const r=requests.find(x=>x.id===id);if(!r)return;const app=apps.find(a=>a.id===r.applicationId||a.ackNo===r.ackNo);openModal(`<div class="detail-head"><div><span class="eyebrow">Payment Request</span><h2>${esc(r.name||'Customer')}</h2><p>ACK: <b>${esc(r.ackNo)}</b></p></div>${statusBadge(r.status)}</div><div class="detail-grid">${field('Request ID',r.id)}${field('ACK',r.ackNo)}${field('Amount','₹'+Number(r.amount||190))}${field('Mobile',r.phone)}${field('Application',r.applicationType)}${field('UTR',r.utr||'—')}${field('Status',r.status||'pending')}${field('Created',fmtDate(r.createdAt))}</div><div class="detail-actions">${app?`<button class="success" onclick="verifyPayment('${app.id}',true)">Mark Paid</button><button class="danger" onclick="verifyPayment('${app.id}',false)">Reject Payment</button>`:''}<button onclick="editPaymentRequest('${r.id}')">Edit Request</button>${r.paymentScreenshot?`<button onclick="downloadDocJpg('${esc(r.paymentScreenshot)}','PAYMENT_${esc(r.ackNo)}')">Download Proof JPG</button>`:''}</div>`)};
window.viewRequest=viewRequest;
function editPaymentRequest(id){const r=requests.find(x=>x.id===id);if(!r)return;openModal(`<h2>Edit Payment Request</h2><div class="admin-edit-grid"><div><label>Amount</label><input id="editReqAmount" type="number" min="190" value="${Number(r.amount||190)}"></div><div><label>Status</label><select id="editReqStatus"><option>pending</option><option>customer_marked_paid</option><option>verification_pending</option><option>paid</option><option>rejected</option></select></div><div><label>UTR</label><input id="editReqUtr" value="${esc(r.utr||'')}"></div><div><label>UTR Mode</label><select id="editReqUtrMode"><option value="required">required</option><option value="optional">optional</option></select></div></div><div class="detail-actions"><button onclick="closeModal()">Cancel</button><button class="success" onclick="savePaymentRequestEdit('${id}')">Save</button></div>`);$('editReqStatus').value=r.status||'pending';$('editReqUtrMode').value=r.utrMode||'required'}
async function savePaymentRequestEdit(id){try{const amount=Math.max(190,Number($('editReqAmount').value||190));const status=$('editReqStatus').value;const utr=$('editReqUtr').value.trim();const mode=$('editReqUtrMode').value;const r=requests.find(x=>x.id===id);await db.collection('customerPaymentRequests').doc(id).update({amount, status,paymentStatus:status,utr,utrMode:mode,utrRequired:mode==='required',adminUpdatedAt:firebase.firestore.FieldValue.serverTimestamp(),adminUpdatedBy:adminUser.email});if(r?.applicationId)await db.collection('applications').doc(r.applicationId).update({paymentStatus:status==='paid'?'paid':status,customerPaymentAmount:amount,paymentUtr:utr});toast('Payment request updated');closeModal()}catch(e){toast(e.message,'error')}}
window.editPaymentRequest=editPaymentRequest;window.savePaymentRequestEdit=savePaymentRequestEdit;
/* ================= V3 REMARK PRESETS ================= */
const V3_REMARKS_KEY='ts_pan_remark_presets';
async function loadRemarkPresets(){try{const snap=await db.collection('remarkPresets').orderBy('createdAt','asc').get();return snap.docs.map(d=>({id:d.id,...d.data()}));}catch{return JSON.parse(localStorage.getItem(V3_REMARKS_KEY)||'[]')}}
async function saveRemarkPreset(text){text=String(text||'').trim();if(!text)return;try{await db.collection('remarkPresets').add({text,createdAt:firebase.firestore.FieldValue.serverTimestamp(),createdBy:adminUser.email});}catch{const a=JSON.parse(localStorage.getItem(V3_REMARKS_KEY)||'[]');if(!a.includes(text))a.push(text);localStorage.setItem(V3_REMARKS_KEY,JSON.stringify(a))}}
async function v3OpenRemark(id,status){const a=apps.find(x=>x.id===id);if(!a)return;const presets=await loadRemarkPresets();openModal(`<h2>Update Status & Remark</h2><div class="admin-edit-grid"><div><label>Status<select id="v3RemarkStatus"><option>pending</option><option>under process</option><option>approved</option><option>rejected</option></select></label></div><div><label>Saved Remark<select id="v3RemarkPreset"><option value="">Select saved remark</option>${presets.map(x=>`<option>${esc(x.text)}</option>`).join('')}</select></label></div></div><label>Remark<textarea id="v3RemarkText" rows="4" placeholder="Enter remark…">${esc(a.remark||'')}</textarea></label><div class="detail-actions"><button onclick="closeModal()">Cancel</button><button class="primary" onclick="v3SaveStatusRemark('${id}')">Update Status</button></div>`);$('v3RemarkStatus').value=status||a.status||'pending';$('v3RemarkPreset').onchange=()=>{if($('v3RemarkPreset').value)$('v3RemarkText').value=$('v3RemarkPreset').value};}
async function v3SaveStatusRemark(id){const status=$('v3RemarkStatus').value,remark=$('v3RemarkText').value.trim();try{if(remark)await saveRemarkPreset(remark);await db.collection('applications').doc(id).update({status,remark,statusUpdatedAt:firebase.firestore.FieldValue.serverTimestamp(),statusUpdatedBy:adminUser.email});logAction('Updated status and remark',id);toast('Status & remark updated');closeModal();loadAll();}catch(e){toast(e.message,'error')}}
window.v3OpenRemark=v3OpenRemark;window.v3SaveStatusRemark=v3SaveStatusRemark;
// Replace application action modal with a dedicated status+remark workflow.
const _v3ViewAppBase=viewApp;
viewApp=async function(id){const a=apps.find(x=>x.id===id);if(!a)return;openModal(`<div class="detail-head"><div><span class="eyebrow">${esc(a.applicationType||'New PAN')}</span><h2>${esc(a.name||'Application')}</h2><p>ACK: <b>${esc(a.ackNo)}</b> • ${fmtDate(a.createdAt)}</p></div><div>${statusBadge(a.status)} ${statusBadge(a.paymentStatus||'pending')}</div></div><div class="detail-actions"><button class="primary" onclick="v3OpenRemark('${id}','under process')">Update Status / Remark</button><button onclick="openDocs('${id}')">Documents</button><button onclick="whatsappApp('${id}')">WhatsApp</button></div><div class="detail-grid">${field('ACK Number',a.ackNo)}${field('Applicant',a.name)}${field('Mobile',a.phone)}${field('Email',a.email)}${field('PAN',a.panNumber||'—')}${field('DOB',a.dob)}${field('Gender',a.gender)}${field("Father's Name (First • Middle • Last)",[a.fatherFirstName,a.fatherMiddleName,a.fatherlastName||a.fatherLastName].filter(Boolean).join(' ')||a.father||a.fatherName||'—')}${field("Mother's Name (First • Middle • Last)",[a.motherFirstName,a.motherMiddleName,a.motherlastName||a.motherLastName].filter(Boolean).join(' ')||a.mother||a.motherName||'—')}${field('Address',[a.flatNo,a.villageCity,a.postOffice,a.subDivision,a.district,a.state,a.pinCode].filter(Boolean).join(', '))}${field('Payment Amount','₹'+Number(a.paymentAmount||190))}${field('UTR',a.paymentUtr||a.utr||'—')}${field('Remark',a.remark||'—')}</div><div class="timeline"><h3>Application Timeline</h3>${timeline(a)}</div>`)};
window.viewApp=viewApp;



/* ================= APPLICATION EDIT ================= */
function splitPersonName(value, first, middle, last){
  const parts=String(value||'').trim().split(/\s+/).filter(Boolean);
  return {first:parts[0]||'',middle:parts.length>2?parts.slice(1,-1).join(' '):'',last:parts.length>1?parts[parts.length-1]:''};
}
function editApplication(id){
  const a=apps.find(x=>x.id===id); if(!a)return;
  const f=(a.firstName||a.first||''); const m=(a.middleName||a.middle||''); const l=(a.lastName||a.last||'');
  const fp=a.fatherFirstName||'', fm=a.fatherMiddleName||'', fl=a.fatherlastName||a.fatherLastName||'';
  const mp=a.motherFirstName||'', mm=a.motherMiddleName||'', ml=a.motherlastName||a.motherLastName||'';
  const fatherSplit=(fp||fm||fl)?{first:fp,middle:fm,last:fl}:splitPersonName(a.father);
  const motherSplit=(mp||mm||ml)?{first:mp,middle:mm,last:ml}:splitPersonName(a.mother);
  const gp=a.guardianFirstName||'', gm=a.guardianMiddleName||'', gl=a.guardianlastName||a.guardianLastName||'';
  const guardianSplit=(gp||gm||gl)?{first:gp,middle:gm,last:gl}:splitPersonName(a.guardianName);
  const v=x=>esc(x??'');
  openModal(`<div class="application-edit-modal"><div class="detail-head"><div><span class="eyebrow">EDIT APPLICATION</span><h2>${v(a.name||'Application')}</h2><p>ACK: <b>${v(a.ackNo)}</b> • ${v(a.applicationType||'New PAN')}</p></div></div>
  <div class="edit-section"><h3>Applicant Details</h3><div class="admin-edit-grid">
    <label>First Name<input id="eaFirst" value="${v(f)}"></label><label>Middle Name<input id="eaMiddle" value="${v(m)}"></label><label>Last Name<input id="eaLast" value="${v(l)}" required></label>
    <label>Name as per Aadhaar<input id="eaNameAadhar" value="${v(a.nameAadhar||a.nameAsPerAadhaar)}"></label><label>Aadhaar Number<input id="eaAadhaar" value="${v(a.aadhaar||a.aadhar)}"></label><label>Date of Birth<input id="eaDob" type="date" value="${v(a.dob)}"></label>
    <label>Gender<select id="eaGender"><option value="">Select</option><option>Male</option><option>Female</option><option>Other</option></select></label><label>Mobile<input id="eaPhone" value="${v(a.phone)}"></label><label>Email<input id="eaEmail" type="email" value="${v(a.email)}"></label>
  </div></div>
  <div class="edit-section"><h3>Father's Name <small>First → Middle → Last</small></h3><div class="admin-edit-grid"><label>First Name<input id="eaFatherFirst" value="${v(fatherSplit.first)}"></label><label>Middle Name<input id="eaFatherMiddle" value="${v(fatherSplit.middle)}"></label><label>Last Name<input id="eaFatherLast" value="${v(fatherSplit.last)}"></label></div></div>
  <div class="edit-section"><h3>Mother's Name <small>First → Middle → Last</small></h3><div class="admin-edit-grid"><label>First Name<input id="eaMotherFirst" value="${v(motherSplit.first)}"></label><label>Middle Name<input id="eaMotherMiddle" value="${v(motherSplit.middle)}"></label><label>Last Name<input id="eaMotherLast" value="${v(motherSplit.last)}"></label></div></div>
  <div class="edit-section"><h3>Address</h3><div class="admin-edit-grid"><label>Flat No / C/O<input id="eaFlat" value="${v(a.flatNo)}"></label><label>Village / City<input id="eaVillage" value="${v(a.villageCity)}"></label><label>Post Office<input id="eaPost" value="${v(a.postOffice)}"></label><label>Sub Division<input id="eaSub" value="${v(a.subDivision)}"></label><label>District<input id="eaDistrict" value="${v(a.district)}"></label><label>State<input id="eaState" value="${v(a.state)}"></label><label>PIN Code<input id="eaPin" value="${v(a.pinCode)}"></label></div></div>
  <div class="edit-section"><h3>Guardian Details</h3><div class="admin-edit-grid"><label>First Name<input id="eaGuardianFirst" value="${v(guardianSplit.first)}"></label><label>Middle Name<input id="eaGuardianMiddle" value="${v(guardianSplit.middle)}"></label><label>Last Name<input id="eaGuardianLast" value="${v(guardianSplit.last)}"></label></div></div>
  <div class="edit-section"><h3>Correction / Other Details</h3><div class="admin-edit-grid"><label>Old PAN<input id="eaPan" value="${v(a.panNumber||a.oldPan||a.corPAN)}"></label><label>Correction Fields<input id="eaCorrectionFields" value="${v(Array.isArray(a.correctionFields)?a.correctionFields.join(', '):(a.correctionFields||''))}"></label></div><label>Other Correction<textarea id="eaOther">${v(a.otherCorrection||a.otherCorrectionDetails||'')}</textarea></label></div>
  <div class="detail-actions"><button onclick="closeModal()">Cancel</button><button class="success" onclick="saveApplicationEdit('${id}')"><i class="fa-solid fa-check"></i> Save Changes</button></div></div>`);
  $('eaGender').value=a.gender||'';
}
async function saveApplicationEdit(id){
  const a=apps.find(x=>x.id===id); if(!a)return;
  const val=id=>document.getElementById(id)?.value?.trim()||'';
  const first=val('eaFirst'), middle=val('eaMiddle'), last=val('eaLast');
  if(!last){toast('Last Name is required','error');return;}
  const father=[val('eaFatherFirst'),val('eaFatherMiddle'),val('eaFatherLast')].filter(Boolean).join(' ');
  const mother=[val('eaMotherFirst'),val('eaMotherMiddle'),val('eaMotherLast')].filter(Boolean).join(' ');
  const guardian=[val('eaGuardianFirst'),val('eaGuardianMiddle'),val('eaGuardianLast')].filter(Boolean).join(' ');
  const correctionRaw=val('eaCorrectionFields');
  const correctionFields=correctionRaw?correctionRaw.split(',').map(x=>x.trim()).filter(Boolean):[];
  const update={firstName:first,middleName:middle,lastName:last,name:[first,middle,last].filter(Boolean).join(' '),nameAadhar:val('eaNameAadhar'),aadhaar:val('eaAadhaar'),dob:val('eaDob'),gender:val('eaGender'),phone:val('eaPhone'),email:val('eaEmail'),father,mother,guardianName:guardian,fatherFirstName:val('eaFatherFirst'),fatherMiddleName:val('eaFatherMiddle'),fatherlastName:val('eaFatherLast'),motherFirstName:val('eaMotherFirst'),motherMiddleName:val('eaMotherMiddle'),motherlastName:val('eaMotherLast'),guardianFirstName:val('eaGuardianFirst'),guardianMiddleName:val('eaGuardianMiddle'),guardianlastName:val('eaGuardianLast'),flatNo:val('eaFlat'),villageCity:val('eaVillage'),postOffice:val('eaPost'),subDivision:val('eaSub'),district:val('eaDistrict'),state:val('eaState'),pinCode:val('eaPin'),panNumber:val('eaPan'),correctionFields,otherCorrection:val('eaOther'),adminEditedAt:firebase.firestore.FieldValue.serverTimestamp(),adminEditedBy:adminUser.email};
  try{await db.collection('applications').doc(id).update(update);logAction('Edited application',a.ackNo);toast('Application updated successfully');closeModal();await loadAll();}catch(e){toast(e.message||'Could not update application','error')}
}
window.editApplication=editApplication;window.saveApplicationEdit=saveApplicationEdit;

/* ================= TECH SOURCE V4 ADMIN WORKFLOW PATCH ================= */
(function(){
  const A$=id=>document.getElementById(id);
  const Aesc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const settingsRef=()=>db.collection('serviceSettings').doc('pan');
  const workflow=[
    ['payment_verification','Payment Verification'],['document_verification','Document Verification'],['under_process','Under Process'],['pan_processing','PAN Processing'],['approved','Approved'],['final_upload','Final PAN Upload'],['completed','Completed']
  ];
  const label={photo:'Photo',signature:'Signature',aadhaarFront:'Aadhaar Front',aadhaarBack:'Aadhaar Back',dobProof:'DOB Proof',guardianFront:'Guardian Aadhaar Front',guardianBack:'Guardian Aadhaar Back',oldPanCopy:'Old PAN Card Copy'};
  const norm2=v=>String(v||'').toLowerCase();
  const stage=(a)=>a.workflowStage||((String(a.paymentStatus||'').toLowerCase()==='paid')?'document_verification':'payment_verification');
  const countBadge=(id,n)=>{const e=A$(id);if(!e)return;e.textContent=n;e.hidden=!n;};

  async function loadV4Settings(){try{const s=await settingsRef().get();const d=s.exists?s.data():{};A$('setBusiness').value=d.businessName||'TECH SOURCE';A$('setUpi').value=d.upiId||'9661905351-3@axl';A$('setFee').value=Number(d.panFee||190);A$('setWhatsapp').value=d.whatsapp||'9661905351';}catch(e){}}
  async function saveV4Settings(){const data={businessName:A$('setBusiness').value.trim()||'TECH SOURCE',upiId:A$('setUpi').value.trim(),panFee:Math.max(1,Number(A$('setFee').value||190)),whatsapp:A$('setWhatsapp').value.trim(),updatedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedBy:adminUser?.email||''};try{await settingsRef().set(data,{merge:true});A$('settingsMsg').textContent='Settings saved to Firebase for all users.';toast('Settings saved');loadV4Remarks();}catch(e){A$('settingsMsg').textContent='Save failed: '+e.message;toast(e.message,'error')}}
  A$('saveSettings').onclick=saveV4Settings;

  async function loadV4Remarks(){const box=A$('remarkPresetList');if(!box)return;try{const s=await db.collection('remarkPresets').orderBy('createdAt','asc').get();const arr=s.docs.map(d=>({id:d.id,...d.data()}));box.innerHTML=arr.map(r=>`<div class="remark-row"><span>${Aesc(r.text)}</span><div class="remark-row-actions"><button type="button" class="mini" onclick="editV4Remark('${r.id}','${Aesc(r.text)}')"><i class="fa fa-pen"></i></button><button type="button" class="mini danger" onclick="deleteV4Remark('${r.id}')"><i class="fa fa-trash"></i></button></div></div>`).join('')||'<div class="empty">No saved remarks.</div>';}catch(e){box.innerHTML='<div class="empty">Remarks unavailable until Firestore rules/index are configured.</div>';}}
  async function addV4Remark(){const input=A$('newRemarkText'),text=input.value.trim();if(!text)return;try{await db.collection('remarkPresets').add({text,createdAt:firebase.firestore.FieldValue.serverTimestamp(),createdBy:adminUser.email});input.value='';toast('Remark added');loadV4Remarks();}catch(e){toast(e.message,'error')}}
  window.deleteV4Remark=async id=>{try{await db.collection('remarkPresets').doc(id).delete();toast('Remark deleted');loadV4Remarks();}catch(e){toast(e.message,'error')}};
window.editV4Remark=async function(id,text){
  const next=prompt('Edit saved remark:',text||'');
  if(next===null)return;
  const value=next.trim(); if(!value){toast('Remark cannot be empty.','error');return;}
  try{await db.collection('remarkPresets').doc(id).update({text:value,updatedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedBy:adminUser?.email||''});toast('Remark updated');loadV4Remarks();}
  catch(e){toast(e.message,'error')}
};
  A$('addRemarkBtn')?.addEventListener('click',addV4Remark);

  function v4RenderBadges(){
    const pendingApps=apps.filter(a=>!['completed','approved'].includes(norm2(stage(a))) && norm2(a.status)!=='rejected').length;
    const payment=apps.filter(a=>String(a.paymentStatus||'').toLowerCase()==='verification_pending').length+requests.filter(r=>['customer_marked_paid','verification_pending'].includes(norm2(r.status))).length;
    const docs=apps.filter(a=>stage(a)==='document_verification'||(Array.isArray(a.rejectedDocuments)&&a.rejectedDocuments.length)).length;
    const req=requests.filter(r=>['pending','customer_marked_paid','verification_pending'].includes(norm2(r.status))).length;
    countBadge('badgeApplications',pendingApps);countBadge('badgePayments',payment);countBadge('badgeDocuments',docs);countBadge('badgeRequests',req);
  }
  const _renderAll=window.renderAll;window.renderAll=function(){_renderAll();v4RenderBadges();v4RenderDeleteList();};

  // Application status + remark workflow. Approval cannot be skipped and final upload is required.
  async function openV4StatusModal(id){const a=apps.find(x=>x.id===id);if(!a)return;const current=stage(a);const currentIdx=Math.max(0,workflow.findIndex(x=>x[0]===current));let remarks=[];try{const s=await db.collection('remarkPresets').orderBy('createdAt','asc').get();remarks=s.docs.map(d=>d.data().text);}catch(e){}
    const options=workflow.map((x,i)=>`<option value="${x[0]}" ${i<currentIdx?'disabled':''}>${x[1]}</option>`).join('');
    openModal(`<div class="v4-status-modal"><span class="eyebrow">WORKFLOW UPDATE</span><h2>${Aesc(a.name||'Application')}</h2><p>ACK: <b>${Aesc(a.ackNo)}</b></p><div class="workflow-current"><span>Current</span><strong>${Aesc(workflow.find(x=>x[0]===current)?.[1]||current)}</strong></div><label>Status / Stage<select id="v4StageSelect">${options}</select></label><label>Saved Remark<select id="v4RemarkSelect"><option value="">Select remark</option>${remarks.map(r=>`<option>${Aesc(r)}</option>`).join('')}</select></label><label>Remark<textarea id="v4RemarkText" rows="3" placeholder="Remark for customer…">${Aesc(a.remark||'')}</textarea></div><div class="detail-actions"><button onclick="closeModal()">Cancel</button><button class="primary" onclick="v4SaveStage('${id}')">Save Update</button></div>`);
    A$('v4StageSelect').value=current;A$('v4RemarkSelect').onchange=()=>{if(A$('v4RemarkSelect').value)A$('v4RemarkText').value=A$('v4RemarkSelect').value;};
  }
  async function v4SaveStage(id){const a=apps.find(x=>x.id===id);if(!a)return;const next=A$('v4StageSelect').value,remark=A$('v4RemarkText').value.trim(),cur=stage(a),ci=workflow.findIndex(x=>x[0]===cur),ni=workflow.findIndex(x=>x[0]===next);if(ni<ci){toast('Previous workflow stage cannot be selected.','error');return;}if(next==='payment_verification'){toast('Payment verification is the first stage.','error');return;}if(next!=='payment_verification'&&String(a.paymentStatus||'').toLowerCase()!=='paid'){toast('Payment must be verified before documents/process.','error');return;}if(['under_process','pan_processing','approved','final_upload','completed'].includes(next)&&!v4AllDocsVerified(a)){toast('All required documents must be verified first.','error');return;}try{const update={workflowStage:next,remark,status:next==='completed'?'completed':next==='approved'?'approved':next==='rejected'?'rejected':'under process',statusUpdatedAt:firebase.firestore.FieldValue.serverTimestamp(),statusUpdatedBy:adminUser.email};if(remark){update.remark=remark;await db.collection('remarkPresets').add({text:remark,createdAt:firebase.firestore.FieldValue.serverTimestamp(),createdBy:adminUser.email}).catch(()=>{});}await db.collection('applications').doc(id).update(update);logAction('Updated workflow stage',`${a.ackNo} → ${next}${remark?' | '+remark:''}`);toast('Workflow updated');closeModal();renderAll();}catch(e){toast(e.message,'error')}}
  function v4AllDocsVerified(a){const docs=v4DocList(a);return docs.length>0&&docs.every(d=>norm2((a.documentStatuses||{})[d.key]||'pending')==='verified');}
  window.v4OpenStatusModal=openV4StatusModal;window.v4SaveStage=v4SaveStage;

  // Payment verification moves the application to document verification only.
  window.verifyPayment=async function(id,ok=true){const a=apps.find(x=>x.id===id);if(!a)return;try{const now=firebase.firestore.FieldValue.serverTimestamp();const update={paymentStatus:ok?'paid':'rejected',paymentVerifiedAt:now,paymentVerifiedBy:adminUser.email,paymentRemark:A$('v4PaymentRemarkText')?.value?.trim()||''};if(ok)update.workflowStage='document_verification';await db.collection('applications').doc(id).update(update);const req=requests.find(r=>r.applicationId===id||r.ackNo===a.ackNo);if(req)await db.collection('customerPaymentRequests').doc(req.id).update({status:ok?'paid':'rejected',paymentStatus:ok?'paid':'rejected',verifiedAt:now,verifiedBy:adminUser.email,remark:update.paymentRemark});logAction(ok?'Verified payment':'Rejected payment',a.ackNo);toast(ok?'Payment verified → Document Verification':'Payment rejected');closeModal();renderAll();}catch(e){toast(e.message,'error')}};

  // Documents with per-document verification/rejection and direct re-upload route.
  function v4DocList(a){const docs=[['photo',a.photo],['signature',a.signature],['aadhaarFront',a.aadhaarFront],['aadhaarBack',a.aadhaarBack],['dobProof',a.dobProof],['guardianFront',a.guardianFront],['guardianBack',a.guardianBack],['oldPanCopy',a.oldPanCopy]].filter(x=>x[1]||((a.rejectedDocuments||[]).some(r=>r.key===x[0])));return docs.map(([key,url])=>({key,url,label:label[key]}));}
  function v4DocCard(a,d){const st=(a.documentStatuses||{})[d.key]||((a.rejectedDocuments||[]).some(x=>x.key===d.key)?'rejected':'pending');const rej=(a.rejectedDocuments||[]).find(x=>x.key===d.key);return `<div class="doc-card v4-doc-card ${st}"><div class="doc-preview">${d.url?`<img src="${Aesc(d.url)}" alt="${Aesc(d.label)}">`:'<div class="doc-missing">No image</div>'}</div><div class="v4-doc-title"><b>${Aesc(d.label)}</b>${statusBadge(st)}</div>${rej?`<div class="doc-reason">${Aesc(rej.remark||'Rejected')}</div>`:''}<div class="doc-actions"><button type="button" onclick="v4ViewImage('${Aesc(d.url||'')}','${Aesc(d.label)}')">View</button>${d.url?`<button type="button" onclick="v4DownloadImage('${Aesc(d.url)}','${Aesc(a.ackNo+'_'+d.label.replace(/\s+/g,'_'))}')">Download</button>`:''}${st!=='verified'?`<button class="success" type="button" onclick="v4VerifyDoc('${a.id}','${d.key}')">Verify</button>`:''}<button class="danger" type="button" onclick="v4RejectDoc('${a.id}','${d.key}')">Reject</button>${st==='rejected'?`<button type="button" onclick="v4OpenAdminDocUpload('${a.id}','${d.key}')">Upload</button>`:''}</div></div>`}
  window.openDocs=function(id){const a=apps.find(x=>x.id===id);if(!a)return;openModal(`<div class="detail-head"><div><span class="eyebrow">DOCUMENT CENTER</span><h2>${Aesc(a.name||'Application')}</h2><p>ACK: ${Aesc(a.ackNo)}</p></div></div><div class="v4-doc-help">Verify each document separately. Rejecting one document lets the customer replace only that document.</div><div class="doc-grid">${v4DocList(a).map(d=>v4DocCard(a,d)).join('')||'<div class="empty">No documents found.</div>'}</div>`)};
  window.v4VerifyDoc=async function(id,key){const a=apps.find(x=>x.id===id);if(!a)return;if(String(a.paymentStatus||'').toLowerCase()!=='paid'){toast('Payment must be verified before document verification.','error');return;}try{const statuses={...(a.documentStatuses||{}),[key]:'verified'};const rejected=(a.rejectedDocuments||[]).filter(x=>x.key!==key);const update={documentStatuses:statuses,rejectedDocuments:rejected,documentUpdatedAt:firebase.firestore.FieldValue.serverTimestamp(),documentUpdatedBy:adminUser.email};const docs=v4DocList({...a,documentStatuses:statuses,rejectedDocuments:rejected});if(String(a.paymentStatus||'').toLowerCase()==='paid'&&docs.length&&docs.every(d=>statuses[d.key]==='verified'))update.workflowStage='under_process';await db.collection('applications').doc(id).update(update);logAction('Verified document',`${a.ackNo} | ${key}`);toast(`${label[key]} verified`);openDocs(id);}catch(e){toast(e.message,'error')}};
  window.v4RejectDoc=async function(id,key){const a=apps.find(x=>x.id===id);if(!a)return;const presets=[];try{const s=await db.collection('remarkPresets').orderBy('createdAt','asc').get();s.forEach(d=>presets.push(d.data().text));}catch(e){}openModal(`<h2>Reject ${Aesc(label[key])}</h2><label>Saved Remark<select id="v4DocRemark"><option value="">Select reason</option>${presets.map(r=>`<option>${Aesc(r)}</option>`).join('')}</select></label><label>Remark<textarea id="v4DocRemarkText" rows="3" placeholder="Why is this document rejected?"></textarea></label><div class="detail-actions"><button onclick="closeModal()">Cancel</button><button class="danger" onclick="v4SaveDocReject('${id}','${key}')">Reject Document</button></div>`);A$('v4DocRemark').onchange=()=>{if(A$('v4DocRemark').value)A$('v4DocRemarkText').value=A$('v4DocRemark').value;};};
  window.v4SaveDocReject=async function(id,key){const a=apps.find(x=>x.id===id),remark=A$('v4DocRemarkText').value.trim()||'Document rejected. Please upload a clearer/correct document.';try{const rej=[...(a.rejectedDocuments||[]).filter(x=>x.key!==key),{key,label:label[key],remark,rejectedAt:new Date().toISOString(),rejectedBy:adminUser.email}];const statuses={...(a.documentStatuses||{}),[key]:'rejected'};await db.collection('applications').doc(id).update({documentStatuses:statuses,rejectedDocuments:rej,workflowStage:'document_verification',remark,status:'pending',statusUpdatedAt:firebase.firestore.FieldValue.serverTimestamp(),statusUpdatedBy:adminUser.email});await db.collection('remarkPresets').add({text:remark,createdAt:firebase.firestore.FieldValue.serverTimestamp(),createdBy:adminUser.email}).catch(()=>{});logAction('Rejected document',`${a.ackNo} | ${key} | ${remark}`);toast('Document rejected — customer can re-upload only this document');closeModal();renderAll();}catch(e){toast(e.message,'error')}};
  window.v4ViewImage=function(url,title){if(!url)return;openModal(`<div class="v4-image-viewer"><span class="eyebrow">${Aesc(title)}</span><img src="${Aesc(url)}" alt="${Aesc(title)}"><div class="detail-actions"><button onclick="closeModal()">Close</button><button class="primary" onclick="v4DownloadImage('${Aesc(url)}','${Aesc(title.replace(/\s+/g,'_'))}')">Download</button></div></div>`)};
  window.v4DownloadImage=async function(url,name){try{const r=await fetch(url);const b=await r.blob();if(!b.type.startsWith('image/'))throw new Error('Only image downloads are allowed.');const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=(name||'document')+'.jpg';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}catch(e){toast('Image download failed: '+e.message,'error')}};
  window.v4OpenAdminDocUpload=function(id,key){const a=apps.find(x=>x.id===id);if(!a)return;openModal(`<h2>Replace ${Aesc(label[key])}</h2><p>ACK: <b>${Aesc(a.ackNo)}</b></p><input id="v4AdminDocFile" type="file" accept="image/jpeg,image/png,image/webp"><p id="v4AdminDocMsg" class="message"></p><div class="detail-actions"><button onclick="closeModal()">Cancel</button><button class="primary" onclick="v4AdminUploadDoc('${id}','${key}')">Upload</button></div>`)};
  window.v4AdminUploadDoc=async function(id,key){const f=A$('v4AdminDocFile')?.files?.[0];if(!f||!f.type.startsWith('image/')){A$('v4AdminDocMsg').textContent='Select an image file.';return;}try{A$('v4AdminDocMsg').textContent='Uploading…';const url=await adminCloudinaryUpload(f,'pan_applications');const a=apps.find(x=>x.id===id);const rej=(a.rejectedDocuments||[]).filter(x=>x.key!==key);const statuses={...(a.documentStatuses||{}),[key]:'pending'};await db.collection('applications').doc(id).update({[key]:url,rejectedDocuments:rej,documentStatuses:statuses,workflowStage:'document_verification'});toast('Replacement uploaded');openDocs(id);}catch(e){A$('v4AdminDocMsg').textContent=e.message||String(e);}};

  // Final PAN upload is image-only and occurs after Approved stage; upload changes stage to completed.
  window.openApproveUpload=function(id){const a=apps.find(x=>x.id===id);if(!a)return;if(String(a.paymentStatus||'').toLowerCase()!=='paid'||!v4AllDocsVerified(a)){toast('Payment and all documents must be verified before final upload.','error');return;}openModal(`<div class="approval-upload"><span class="eyebrow">FINAL PAN CARD</span><h2>Upload Final PAN — ${Aesc(a.name||'')}</h2><p>ACK: <b>${Aesc(a.ackNo)}</b></p><input id="finalPanFile" type="file" accept="image/jpeg,image/png,image/webp"><p id="finalPanMsg" class="message"></p><div class="detail-actions"><button onclick="closeModal()">Cancel</button><button class="success" onclick="uploadFinalPanAndApprove('${id}')">Upload Final PAN</button></div></div>`)};
  window.uploadFinalPanAndApprove=async function(id){const f=A$('finalPanFile')?.files?.[0];if(!f||!f.type.startsWith('image/')){A$('finalPanMsg').textContent='Only JPG, JPEG, PNG or WEBP final PAN image is allowed.';return;}try{A$('finalPanMsg').textContent='Uploading…';const url=await adminCloudinaryUpload(f,'pan_final_cards');const now=firebase.firestore.FieldValue.serverTimestamp();await db.collection('applications').doc(id).update({workflowStage:'completed',status:'completed',documentUrl:url,panCardUrl:url,finalPanCardUploadedAt:now,statusUpdatedAt:now,statusUpdatedBy:adminUser.email});logAction('Final PAN uploaded — completed',apps.find(x=>x.id===id)?.ackNo||id);toast('Final PAN uploaded. Application completed.');closeModal();renderAll();}catch(e){A$('finalPanMsg').textContent=e.message||String(e)}};

  // Override application view with workflow controls.
  window.viewApp=function(id){const a=apps.find(x=>x.id===id);if(!a)return;const st=stage(a);const docs=v4DocList(a);openModal(`<div class="detail-head"><div><span class="eyebrow">${Aesc(a.applicationType||'New PAN')}</span><h2>${Aesc(a.name||'Application')}</h2><p>ACK: <b>${Aesc(a.ackNo)}</b> • ${fmtDate(a.createdAt)}</p></div><div>${statusBadge(st)} ${statusBadge(a.paymentStatus||'pending')}</div></div><div class="workflow-strip">${workflow.map((x,i)=>`<div class="wf-step ${i<=workflow.findIndex(y=>y[0]===st)?'done':''}"><span>${i+1}</span><small>${Aesc(x[1])}</small></div>`).join('')}</div><div class="detail-actions">${String(a.paymentStatus||'').toLowerCase()==='verification_pending'?`<button class="success" onclick="verifyPayment('${id}',true)">Verify Payment</button><button class="danger" onclick="verifyPayment('${id}',false)">Reject Payment</button>`:''}<button class="primary" onclick="v4OpenStatusModal('${id}')">Status / Remark</button><button class="primary" onclick="editApplication('${id}')"><i class="fa-solid fa-pen"></i> Edit</button><button onclick="openDocs('${id}')">Documents</button><button onclick="whatsappApp('${id}')">WhatsApp</button>${st==='approved'?`<button class="success" onclick="openApproveUpload('${id}')">Final PAN Upload</button>`:''}</div><div class="detail-grid">${field('ACK Number',a.ackNo)}${field('Applicant',a.name)}${field('Mobile',a.phone)}${field('Email',a.email)}${field('PAN',a.panNumber||'—')}${field('DOB',a.dob)}${field('Gender',a.gender)}${field("Father's Name (First • Middle • Last)",[a.fatherFirstName,a.fatherMiddleName,a.fatherlastName||a.fatherLastName].filter(Boolean).join(' ')||a.father||a.fatherName||'—')}${field("Mother's Name (First • Middle • Last)",[a.motherFirstName,a.motherMiddleName,a.motherlastName||a.motherLastName].filter(Boolean).join(' ')||a.mother||a.motherName||'—')}${field('Address',[a.flatNo,a.villageCity,a.postOffice,a.subDivision,a.district,a.state,a.pinCode].filter(Boolean).join(', '))}${field('Payment Amount','₹'+Number(a.paymentAmount||a.customerPaymentAmount||190))}${field('UTR',a.paymentUtr||a.utr||'—')}${field('Remark',a.remark||'—')}</div><div class="subpanel"><h3>Documents</h3><p>${docs.filter(d=>(a.documentStatuses||{})[d.key]==='verified').length}/${docs.length} verified</p></div>`)};

  // Delete Applications: ACK confirmation + complete Firestore cleanup for linked records.
  async function v4DeleteCandidates(){const q=norm2(A$('deleteSearch')?.value);const list=apps.filter(a=>!q||[a.ackNo,a.name,a.phone,a.email,a.panNumber].some(v=>norm2(v).includes(q)));const box=A$('deleteApplicationsTable');if(!box)return;box.innerHTML=list.map(a=>`<article class="delete-app-card"><img src="${Aesc(a.photo||'https://ui-avatars.com/api/?name=TS&background=dc2626&color=fff')}" alt=""><div><b>${Aesc(a.name||'Application')}</b><span>ACK: ${Aesc(a.ackNo||'—')}</span><span>${Aesc(a.applicationType||'New PAN')} • ${Aesc(stage(a))}</span></div><button class="danger" onclick="v4ConfirmDelete('${a.id}')"><i class="fa fa-trash-can"></i> Delete</button></article>`).join('')||'<div class="empty">No applications found.</div>'}
  window.v4ConfirmDelete=function(id){const a=apps.find(x=>x.id===id);if(!a)return;openModal(`<div class="delete-confirm-modal"><div class="delete-icon"><i class="fa fa-trash-can"></i></div><span class="eyebrow">PERMANENT DELETE</span><h2>Delete Application?</h2><div class="delete-identity"><img src="${Aesc(a.photo||'https://ui-avatars.com/api/?name=TS&background=dc2626&color=fff')}" alt=""><div><b>${Aesc(a.name||'—')}</b><span>ACK: ${Aesc(a.ackNo||'—')}</span></div></div><p>This will permanently delete this application's Firestore records, payment-link/request records and related application activity.</p><label>Enter exact ACK: <input id="v4DeleteAck" autocomplete="off" placeholder="${Aesc(a.ackNo||'')}"></label><p id="v4DeleteMsg" class="delete-error"></p><div class="detail-actions"><button onclick="closeModal()">Cancel</button><button class="danger" onclick="v4DeleteApplication('${id}')">Delete Permanently</button></div></div>`)};
  window.v4DeleteApplication=async function(id){const a=apps.find(x=>x.id===id),input=A$('v4DeleteAck'),msg=A$('v4DeleteMsg');if(!a)return;if(input.value.trim().toUpperCase()!==(a.ackNo||'').toUpperCase()){msg.textContent='Wrong ACK. Please enter the exact ACK shown above.';return;}try{const targets=[db.collection('applications').doc(id)];const req1=await db.collection('customerPaymentRequests').where('applicationId','==',id).get();req1.forEach(d=>targets.push(d.ref));const req2=await db.collection('customerPaymentRequests').where('ackNo','==',a.ackNo).get();req2.forEach(d=>targets.push(d.ref));const acts=await db.collection('adminActivity').limit(1000).get();acts.forEach(d=>{const x=d.data()||{};if(String(x.detail||'').includes(String(a.ackNo||'')))targets.push(d.ref);});const unique=[...new Map(targets.map(r=>[r.path,r])).values()];for(let i=0;i<unique.length;i+=450){const batch=db.batch();unique.slice(i,i+450).forEach(ref=>batch.delete(ref));await batch.commit();}logAction('Deleted application',a.ackNo);toast('Application and related Firestore records deleted');closeModal();renderAll();}catch(e){msg.textContent='Delete failed: '+(e.message||e)}};
  function v4RenderDeleteList(){if(A$('deleteApplications'))v4DeleteCandidates();}
  A$('deleteSearch')?.addEventListener('input',v4RenderDeleteList);

  // Search docs section should use the same secure document viewer.

  // Initialize.
  setTimeout(()=>{loadV4Settings();loadV4Remarks();v4RenderBadges();v4RenderDeleteList();},250);
})();
/* V4 admin payment retry routing + rejected-link recovery */
(function(){
  window.v4OpenPaymentRetryFromAdmin=async function(id){const a=apps.find(x=>x.id===id);if(!a)return;try{const r=requests.find(x=>x.applicationId===id||x.ackNo===a.ackNo);if(r){window.open((window.location.origin+window.location.pathname)+'?customerPayId='+encodeURIComponent(r.id),'_blank');}else{window.open((window.location.origin+window.location.pathname)+'?customerPay='+encodeURIComponent(a.ackNo),'_blank');}}catch(e){toast(e.message||String(e),'error')}};
  const oldView=window.viewApp;
  // Patch only the action button by wrapping the current rendered modal content.
  const baseView=oldView;
  window.viewApp=function(id){baseView(id);setTimeout(()=>{const a=apps.find(x=>x.id===id);if(!a||String(a.paymentStatus||'').toLowerCase()!=='rejected')return;const box=document.querySelector('#modalBody .detail-actions');if(!box)return;const b=document.createElement('button');b.className='primary';b.textContent='Open Payment Page';b.onclick=()=>v4OpenPaymentRetryFromAdmin(id);box.appendChild(b);},0)};
})();

/* TECH SOURCE FINAL ADMIN PATCH */
(function(){
  const escF=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const labelsF={photo:'Photo',signature:'Signature',aadhaarFront:'Aadhaar Front',aadhaarBack:'Aadhaar Back',dobProof:'DOB Proof',guardianFront:'Guardian Aadhaar Front',guardianBack:'Guardian Aadhaar Back',oldPanCopy:'Old PAN Card Copy'};
  const workflowF=[['payment_verification','Payment Verification'],['document_verification','Document Verification'],['under_process','Under Process'],['pan_processing','PAN Processing'],['approved','Approved'],['final_upload','Final PAN Upload'],['completed','Completed']];
  function docKeysF(a){
    const keys=['photo','signature','aadhaarFront','aadhaarBack','dobProof'];
    if(a.guardianFront)keys.push('guardianFront');
    if(a.guardianBack)keys.push('guardianBack');
    if(a.oldPanCopy)keys.push('oldPanCopy');
    return keys;
  }
  function isFullyVerifiedF(a){const keys=docKeysF(a),s=a.documentStatuses||{};return keys.length>0&&keys.every(k=>String(s[k]||'pending').toLowerCase()==='verified');}
  function refreshDocSelectorF(){
    const sel=$('docApplicationSelect'); if(!sel)return;
    const keep=sel.value;
    const eligible=apps.filter(a=>!isFullyVerifiedF(a));
    sel.innerHTML='<option value="">Select application</option>'+eligible.map(a=>`<option value="${escF(a.id)}">${escF(a.ackNo||'No ACK')} — ${escF(a.name||'Application')}</option>`).join('');
    if(eligible.some(a=>a.id===keep))sel.value=keep;
    if(!keep && eligible.length===1)sel.value=eligible[0].id;
  }
  function renderSelectedDocsF(id){
    const box=$('documentResult'); if(!box)return;
    if(!id){box.classList.add('empty');box.innerHTML='Select an application to view documents.';return;}
    const a=apps.find(x=>x.id===id); if(!a){box.classList.add('empty');box.innerHTML='Application not found.';return;}
    box.classList.remove('empty');
    // Use the existing secure document viewer so View/Download/Verify/Reject/Upload actions stay identical.
    if(window.openDocs){window.openDocs(a.id);return;}
  }
  $('docApplicationSelect')?.addEventListener('change',e=>renderSelectedDocsF(e.target.value));
  const oldRenderAllF=window.renderAll;
  window.renderAll=function(){oldRenderAllF?.();refreshDocSelectorF();};
  // Strict next-stage enforcement: no stage skipping and final completion only after final PAN upload.
  window.v4OpenStatusModal=async function(id){
    const a=apps.find(x=>x.id===id); if(!a)return;
    const current=String(a.workflowStage||((String(a.paymentStatus||'').toLowerCase()==='paid')?'document_verification':'payment_verification')).toLowerCase();
    const idx=workflowF.findIndex(x=>x[0]===current);
    const next=workflowF[idx+1];
    let remarks=[];
    try{const s=await db.collection('remarkPresets').orderBy('createdAt','asc').get();remarks=s.docs.map(d=>String(d.data().text||'')).filter(Boolean);}catch(e){}
    const isManual=next && ['under_process','pan_processing','approved'].includes(next[0]);
    if(!next){toast('Application is already at the final stage.','error');return;}
    let html=`<div class="v4-status-modal"><span class="eyebrow">NEXT WORKFLOW STEP</span><h2>${escF(a.name||'Application')}</h2><p>ACK: <b>${escF(a.ackNo)}</b></p><div class="workflow-current"><span>Current</span><strong>${escF(workflowF[idx]?.[1]||current)}</strong></div><div class="next-stage-note">Next allowed stage: <b>${escF(next[1])}</b></div>`;
    if(isManual){html+=`<label>Remark<select id="v4RemarkSelect"><option value="">Select saved remark</option>${remarks.map(r=>`<option value="${escF(r)}">${escF(r)}</option>`).join('')}</select></label><label>Customer Remark<textarea id="v4RemarkText" rows="3" placeholder="Optional remark for customer…">${escF(a.remark||'')}</textarea></label>`;}
    html+=`<div class="detail-actions"><button onclick="closeModal()">Cancel</button><button class="primary" onclick="v4SaveStage('${escF(id)}')">Move to ${escF(next[1])}</button></div></div>`;
    openModal(html);
    $('v4RemarkSelect')?.addEventListener('change',e=>{if(e.target.value)$('v4RemarkText').value=e.target.value;});
  };
  window.v4SaveStage=async function(id){
    const a=apps.find(x=>x.id===id);if(!a)return;
    const cur=String(a.workflowStage||((String(a.paymentStatus||'').toLowerCase()==='paid')?'document_verification':'payment_verification')).toLowerCase();
    const ci=workflowF.findIndex(x=>x[0]===cur), next=workflowF[ci+1];
    if(!next){toast('No further workflow step is available.','error');return;}
    if(next[0]==='document_verification'){toast('Payment verification must be completed first.','error');return;}
    if(String(a.paymentStatus||'').toLowerCase()!=='paid'){toast('Payment must be verified before continuing.','error');return;}
    if(next[0]==='under_process'&&!docKeysF(a).every(k=>String((a.documentStatuses||{})[k]||'pending').toLowerCase()==='verified')){toast('All required documents must be verified first.','error');return;}
    if(next[0]==='completed'){toast('Completed is set automatically after final PAN upload.','error');return;}
    const remark=$('v4RemarkText')?.value?.trim()||'';
    try{
      const update={workflowStage:next[0],status:next[0]==='approved'?'approved':'under process',statusUpdatedAt:firebase.firestore.FieldValue.serverTimestamp(),statusUpdatedBy:adminUser.email};
      if(remark)update.remark=remark;
      await db.collection('applications').doc(id).update(update);
      logAction('Moved workflow stage',`${a.ackNo} → ${next[0]}${remark?' | '+remark:''}`);
      toast(`Moved to ${next[1]}`);closeModal();renderAll();
    }catch(e){toast(e.message||String(e),'error');}
  };
  // Payment verification always starts document verification; payment rejection remains retryable.
  window.verifyPayment=async function(id,ok=true){
    const a=apps.find(x=>x.id===id);if(!a)return;
    const save=async remark=>{
      try{
        const now=firebase.firestore.FieldValue.serverTimestamp();
        const update={paymentStatus:ok?'paid':'rejected',paymentVerifiedAt:now,paymentVerifiedBy:adminUser.email,paymentRemark:remark||''};
        if(ok)update.workflowStage='document_verification';
        await db.collection('applications').doc(id).update(update);
        const req=requests.find(r=>r.applicationId===id||r.ackNo===a.ackNo);
        if(req)await db.collection('customerPaymentRequests').doc(req.id).update({status:ok?'paid':'rejected',paymentStatus:ok?'paid':'rejected',verifiedAt:now,verifiedBy:adminUser.email,remark:remark||''});
        logAction(ok?'Verified payment':'Rejected payment',`${a.ackNo}${remark?' | '+remark:''}`);toast(ok?'Payment verified → Document Verification':'Payment rejected');closeModal();renderAll();
      }catch(e){toast(e.message||String(e),'error');}
    };
    if(ok){await save('');return;}
    let remarks=[];try{const s=await db.collection('remarkPresets').orderBy('createdAt','asc').get();remarks=s.docs.map(d=>String(d.data().text||'')).filter(Boolean);}catch(e){}
    openModal(`<div class="v4-status-modal"><span class="eyebrow">PAYMENT REJECTION</span><h2>${escF(a.name||'Customer')}</h2><p>ACK: <b>${escF(a.ackNo)}</b></p><label>Saved Remark<select id="v4PayRemarkSelect"><option value="">Select remark</option>${remarks.map(r=>`<option value="${escF(r)}">${escF(r)}</option>`).join('')}</select></label><label>Remark<textarea id="v4PayRemarkText" rows="3" placeholder="Payment rejection reason…"></textarea></label><div class="detail-actions"><button onclick="closeModal()">Cancel</button><button class="danger" id="v4PayRejectConfirm">Reject Payment</button></div></div>`);
    $('v4PayRemarkSelect').onchange=()=>{if($('v4PayRemarkSelect').value)$('v4PayRemarkText').value=$('v4PayRemarkSelect').value;};
    $('v4PayRejectConfirm').onclick=()=>save($('v4PayRemarkText').value.trim());
  };
  // Ensure the selector is ready immediately and after live snapshots.
  setTimeout(refreshDocSelectorF,300);
})();
