const firebaseConfig = {
  apiKey: "AIzaSyDm3NcIjnLestNntscRXbeChvEwwqxkg8E",
  authDomain: "zoprint-c4891.firebaseapp.com",
  databaseURL: "https://zoprint-c4891-default-rtdb.firebaseio.com",
  projectId: "zoprint-c4891",
  storageBucket: "zoprint-c4891.firebasestorage.app",
  messagingSenderId: "944996490044",
  appId: "1:944996490044:web:ccfc3cfacc4acd04d45c39",
  measurementId: "G-CVWYCKMN01"
};
firebase.initializeApp(firebaseConfig);const auth=firebase.auth(),db=firebase.firestore();
let adminUser=null,apps=[],requests=[],activity=[];let unsubApps=null,unsubReq=null;
const $=id=>document.getElementById(id); const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=v=>{if(!v)return '—';const d=v.toDate? v.toDate():new Date(v);return isNaN(d)?'—':d.toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});};
const norm=v=>String(v||'').toLowerCase(); const statusBadge=v=>`<span class="badge ${norm(v).replace(/[^a-z]+/g,'-')}">${esc(v||'pending')}</span>`;
function toast(m,type='ok'){const t=$('toast');t.textContent=m;t.className='show '+type;setTimeout(()=>t.className='',2600)}
function openModal(html){$('modalBody').innerHTML=html;$('modal').classList.remove('hidden')}function closeModal(){$('modal').classList.add('hidden')}
window.closeModal=closeModal;
function logAction(action,detail=''){if(!adminUser)return;db.collection('adminActivity').add({adminUid:adminUser.uid,adminEmail:adminUser.email,action,detail,createdAt:firebase.firestore.FieldValue.serverTimestamp()}).catch(()=>{})}
async function ensureAdmin(user){const s=await db.collection('users').doc(user.uid).get();const d=s.exists?s.data():{};return d.role==='admin'||d.isAdmin===true||d.admin===true}
auth.onAuthStateChanged(async user=>{if(!user){$('loginView').classList.remove('hidden');$('app').classList.add('hidden');return}try{if(!(await ensureAdmin(user))){await auth.signOut();$('loginMsg').textContent='Access denied: admin account required.';return}adminUser=user;$('loginView').classList.add('hidden');$('app').classList.remove('hidden');$('adminName').textContent=user.displayName||'Administrator';$('adminEmail').textContent=user.email||'';$('adminAvatar').textContent=(user.displayName||user.email||'A').charAt(0).toUpperCase();$('settingsEmail').textContent=user.email||'—';startLive();loadActivity();loadSettings()}catch(e){await auth.signOut();$('loginMsg').textContent='Could not verify admin access.'}});
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginMsg').textContent='';try{await auth.signInWithEmailAndPassword($('email').value.trim(),$('password').value)}catch(e){$('loginMsg').textContent=e.message.replace('Firebase:','').trim()}});$('logoutBtn').onclick=()=>auth.signOut();$('refreshBtn').onclick=()=>{renderAll();loadActivity();toast('Refreshed')};
function startLive(){unsubApps?.();unsubReq?.();unsubApps=db.collection('applications').orderBy('createdAt','desc').onSnapshot(s=>{apps=s.docs.map(d=>({id:d.id,...d.data()}));renderAll();$('lastUpdated').textContent='Updated '+new Date().toLocaleTimeString('en-IN')},e=>toast('Applications load error: '+e.message,'error'));unsubReq=db.collection('customerPaymentRequests').orderBy('createdAt','desc').onSnapshot(s=>{requests=s.docs.map(d=>({id:d.id,...d.data()}));renderAll()},e=>toast('Payment requests error: '+e.message,'error'))}
function renderAll(){renderStats();renderRecent();renderApps();renderPayments();renderRequests();}
function renderStats(){const pending=apps.filter(a=>norm(a.status)==='pending').length,under=apps.filter(a=>norm(a.status)==='under process').length,approved=apps.filter(a=>norm(a.status)==='approved').length,rejected=apps.filter(a=>norm(a.status)==='rejected').length,paid=apps.filter(a=>norm(a.paymentStatus)==='paid').length,verify=apps.filter(a=>norm(a.paymentStatus)==='verification_pending').length;const amount=apps.filter(a=>norm(a.paymentStatus)==='paid').reduce((n,a)=>n+Number(a.paymentAmount||190),0);$('statsCards').innerHTML=[['Total Applications',apps.length,'fa-folder-open'],['Pending',pending,'fa-hourglass-half'],['Under Process',under,'fa-arrows-rotate'],['Approved',approved,'fa-circle-check'],['Rejected',rejected,'fa-circle-xmark'],['Payment Pending',verify,'fa-money-bill-transfer'],['Paid Applications',paid,'fa-circle-check'],['Verified Amount','₹'+amount.toLocaleString('en-IN'),'fa-indian-rupee-sign']].map(x=>`<div class="stat"><i class="fa-solid ${x[2]}"></i><div><span>${x[0]}</span><b>${x[1]}</b></div></div>`).join('')}
function renderRecent(){const rows=apps.slice(0,7).map(a=>`<tr><td><b>${esc(a.ackNo)}</b><small>${esc(a.applicationType||'New PAN')}</small></td><td>${esc(a.name||'—')}</td><td>${statusBadge(a.status)}</td><td>${statusBadge(a.paymentStatus||'pending')}</td><td><button class="mini" onclick="viewApp('${a.id}')">View</button></td></tr>`).join('');$('recentApps').innerHTML=table(['ACK / Type','Applicant','Status','Payment',''],rows);$('recentPayments').innerHTML=apps.filter(a=>norm(a.paymentStatus)==='verification_pending').slice(0,6).map(a=>`<div class="pay-row"><div><b>${esc(a.ackNo)}</b><span>${esc(a.name||'—')} • ₹${Number(a.paymentAmount||190)}</span></div><button class="mini primary" onclick="viewApp('${a.id}')">Review</button></div>`).join('')||'<div class="empty">No payments awaiting verification.</div>'}
function table(head,rows){return `<table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||'<tr><td colspan="9" class="empty">No records found.</td></tr>'}</tbody></table>`}
function renderApps(){const q=norm($('appSearch').value),st=$('appStatus').value,p=$('appPay').value,ty=$('appType').value;const list=apps.filter(a=>(!q||[a.ackNo,a.name,a.phone,a.panNumber,a.email].some(v=>norm(v).includes(q)))&&(st==='all'||norm(a.status)===norm(st))&&(p==='all'||norm(a.paymentStatus)===norm(p))&&(ty==='all'||(a.applicationType||'New PAN')===ty));$('applicationsTable').innerHTML=table(['ACK / Date','Applicant','Mobile','Type','Status','Payment','Amount','Action'],list.map(a=>`<tr><td><b>${esc(a.ackNo)}</b><small>${fmtDate(a.createdAt)}</small></td><td>${esc(a.name||'—')}</td><td>${esc(a.phone||'—')}</td><td>${esc(a.applicationType||'New PAN')}</td><td>${statusBadge(a.status)}</td><td>${statusBadge(a.paymentStatus||'pending')}</td><td>₹${Number(a.paymentAmount||190).toLocaleString('en-IN')}</td><td><button class="mini primary" onclick="viewApp('${a.id}')">Open</button></td></tr>`).join(''))}
function renderPayments(){const q=norm($('paySearch').value),f=$('payFilter').value;const list=apps.filter(a=>(f==='all'||norm(a.paymentStatus)===norm(f))&&(!q||[a.ackNo,a.name,a.paymentUtr,a.utr].some(v=>norm(v).includes(q))));$('paymentsTable').innerHTML=table(['ACK','Applicant','Amount','UTR','Payment','Submitted','Action'],list.map(a=>`<tr><td><b>${esc(a.ackNo)}</b></td><td>${esc(a.name||'—')}</td><td>₹${Number(a.paymentAmount||190)}</td><td>${esc(a.paymentUtr||a.utr||'—')}</td><td>${statusBadge(a.paymentStatus||'pending')}</td><td>${fmtDate(a.paymentSubmittedAt||a.customerSubmittedAt)}</td><td><button class="mini primary" onclick="viewApp('${a.id}')">Review</button></td></tr>`).join(''))}
function renderRequests(){const q=norm($('reqSearch').value),f=$('reqFilter').value;const list=requests.filter(r=>(f==='all'||norm(r.status)===norm(f))&&(!q||[r.ackNo,r.name,r.phone,r.id,r.utr].some(v=>norm(v).includes(q))));$('requestsTable').innerHTML=table(['Request','ACK','Customer','Amount','UTR','Status','Created','Action'],list.map(r=>`<tr><td><b>${esc(r.id.slice(0,10))}</b></td><td>${esc(r.ackNo)}</td><td>${esc(r.name||'—')}</td><td>₹${Number(r.amount||190)}</td><td>${esc(r.utr||'—')}</td><td>${statusBadge(r.status)}</td><td>${fmtDate(r.createdAt)}</td><td><button class="mini primary" onclick="viewRequest('${r.id}')">Open</button></td></tr>`).join(''))}
['appSearch','appStatus','appPay','appType','paySearch','payFilter','reqSearch','reqFilter'].forEach(id=>$(id).addEventListener('input',renderAll));
['appStatus','appPay','appType','payFilter','reqFilter'].forEach(id=>$(id).addEventListener('change',renderAll));
async function viewApp(id){const a=apps.find(x=>x.id===id);if(!a)return;logAction('Viewed application',a.ackNo);openModal(`<div class="detail-head"><div><span class="eyebrow">${esc(a.applicationType||'New PAN')}</span><h2>${esc(a.name||'Application')}</h2><p>ACK: <b>${esc(a.ackNo)}</b> • ${fmtDate(a.createdAt)}</p></div><div>${statusBadge(a.status)} ${statusBadge(a.paymentStatus||'pending')}</div></div><div class="detail-actions"><button class="primary" onclick="setAppStatus('${id}','under process')">Under Process</button><button class="success" onclick="setAppStatus('${id}','approved')">Approve</button><button class="danger" onclick="setAppStatus('${id}','rejected')">Reject</button><button onclick="openDocs('${id}')">Documents</button><button onclick="whatsappApp('${id}')">WhatsApp</button></div><div class="detail-grid">${field('ACK Number',a.ackNo)}${field('Applicant',a.name)}${field('Mobile',a.phone)}${field('Email',a.email)}${field('PAN',a.panNumber||'—')}${field('DOB',a.dob)}${field('Gender',a.gender)}${field('Father',a.father||a.fatherName)}${field('Mother',a.mother||a.motherName)}${field('Address',[a.flatNo,a.villageCity,a.postOffice,a.subDivision,a.district,a.state,a.pinCode].filter(Boolean).join(', '))}${field('Payment Amount','₹'+Number(a.paymentAmount||190))}${field('UTR',a.paymentUtr||a.utr||'—')}${field('Created',fmtDate(a.createdAt))}</div>${a.correctionFields?`<div class="subpanel"><h3>Correction Fields</h3><p>${esc(Array.isArray(a.correctionFields)?a.correctionFields.join(', '):a.correctionFields)}</p></div>`:''}<div class="timeline"><h3>Application Timeline</h3>${timeline(a)}</div>`)}
function field(k,v){return `<div class="field"><span>${esc(k)}</span><b>${esc(v||'—')}</b></div>`}function timeline(a){const st=norm(a.status);const paid=norm(a.paymentStatus)==='paid';return [['Application Submitted',true],['Payment Verified',paid],['Under Process',['under process','approved'].includes(st)],['Approved',st==='approved'],['Rejected',st==='rejected']].map(x=>`<div class="tl ${x[1]?'done':''}"><i class="fa-solid ${x[1]?'fa-check':'fa-circle'}"></i><span>${x[0]}</span></div>`).join('')}
async function setAppStatus(id,status){try{await db.collection('applications').doc(id).update({status,statusUpdatedAt:firebase.firestore.FieldValue.serverTimestamp(),statusUpdatedBy:adminUser.email});logAction('Changed application status',`${id} → ${status}`);toast('Status updated');closeModal()}catch(e){toast(e.message,'error')}}
async function verifyPayment(id,ok=true){const a=apps.find(x=>x.id===id);if(!a)return;try{await db.collection('applications').doc(id).update({paymentStatus:ok?'paid':'rejected',paymentVerifiedAt:firebase.firestore.FieldValue.serverTimestamp(),paymentVerifiedBy:adminUser.email});const req=requests.find(r=>r.applicationId===id||r.ackNo===a.ackNo);if(req)await db.collection('customerPaymentRequests').doc(req.id).update({status:ok?'paid':'rejected',paymentStatus:ok?'paid':'rejected',verifiedAt:firebase.firestore.FieldValue.serverTimestamp(),verifiedBy:adminUser.email});logAction(ok?'Verified payment':'Rejected payment',a.ackNo);toast(ok?'Payment verified':'Payment rejected');closeModal()}catch(e){toast(e.message,'error')}}
function viewRequest(id){const r=requests.find(x=>x.id===id);if(!r)return;const app=apps.find(a=>a.id===r.applicationId||a.ackNo===r.ackNo);openModal(`<div class="detail-head"><div><span class="eyebrow">Payment Request</span><h2>${esc(r.name||'Customer')}</h2><p>ACK: <b>${esc(r.ackNo)}</b></p></div>${statusBadge(r.status)}</div><div class="detail-grid">${field('Request ID',r.id)}${field('Amount','₹'+Number(r.amount||190))}${field('Mobile',r.phone)}${field('Application',r.applicationType)}${field('UTR',r.utr||'—')}${field('Created',fmtDate(r.createdAt))}</div><div class="detail-actions"><button class="success" onclick="${app?`verifyPayment('${app.id}',true)`:''}">Verify Payment</button><button class="danger" onclick="${app?`verifyPayment('${app.id}',false)`:''}">Reject Payment</button>${r.paymentScreenshot?`<a class="button" href="${esc(r.paymentScreenshot)}" target="_blank">Payment Proof</a>`:''}</div>`)}
function openDocs(id){const a=apps.find(x=>x.id===id);if(!a)return;const docs=[['Photo',a.photo],['Signature',a.signature],['Aadhaar Front',a.aadhaarFront],['Aadhaar Back',a.aadhaarBack],['DOB Proof',a.dobProof],['Guardian Front',a.guardianFront],['Guardian Back',a.guardianBack]].filter(d=>d[1]);openModal(`<div class="detail-head"><div><span class="eyebrow">Document Center</span><h2>${esc(a.name||'Application')}</h2><p>ACK: ${esc(a.ackNo)} • ${esc(a.applicationType||'PAN')}</p></div></div><div class="doc-grid">${docs.map(d=>`<div class="doc-card"><div class="doc-preview"><img src="${esc(d[1])}" alt="${esc(d[0])}"></div><b>${esc(d[0])}</b><div class="doc-actions"><a href="${esc(d[1])}" target="_blank">Open</a><button onclick="downloadDocJpg('${esc(d[1])}','${esc(a.ackNo+'_'+d[0].replace(/\s+/g,'_'))}')">Download JPG</button></div></div>`).join('')||'<div class="empty">No documents found.</div>'}</div>`)}
function whatsappApp(id){const a=apps.find(x=>x.id===id);if(!a)return;const msg=`TECH SOURCE PAN Update%0AACK: ${a.ackNo}%0AName: ${a.name||''}%0AApplication: ${a.applicationType||'New PAN'}%0AStatus: ${a.status||'pending'}%0APayment: ${a.paymentStatus||'pending'}`;window.open('https://wa.me/'+String(a.phone||'').replace(/\D/g,'')+'?text='+msg,'_blank');logAction('Opened WhatsApp',a.ackNo)}
window.viewApp=viewApp;window.viewRequest=viewRequest;window.verifyPayment=verifyPayment;window.setAppStatus=setAppStatus;window.openDocs=openDocs;window.whatsappApp=whatsappApp;
$('docSearch').addEventListener('input',()=>{const q=norm($('docSearch').value);const a=apps.find(x=>norm(x.ackNo)===q||norm(x.ackNo).includes(q));if(!q){$('documentResult').innerHTML='Search an application to view documents.';return}if(!a){$('documentResult').innerHTML='<div class="empty">No application found.</div>';return}const docs=[['Photo',a.photo],['Signature',a.signature],['Aadhaar Front',a.aadhaarFront],['Aadhaar Back',a.aadhaarBack],['DOB Proof',a.dobProof],['Guardian Front',a.guardianFront],['Guardian Back',a.guardianBack]].filter(x=>x[1]);$('documentResult').classList.remove('empty');$('documentResult').innerHTML=docs.map(d=>`<div class="doc-card"><div class="doc-preview"><img src="${esc(d[1])}" alt="${esc(d[0])}"></div><b>${esc(d[0])}</b><a href="${esc(d[1])}" target="_blank">Open / Download</a></div>`).join('')||'<div class="empty">No documents.</div>'});
async function loadActivity(){if(!adminUser)return;try{const s=await db.collection('adminActivity').orderBy('createdAt','desc').limit(100).get();activity=s.docs.map(d=>d.data());$('activityTable').innerHTML=table(['Time','Admin','Action','Detail'],activity.map(x=>`<tr><td>${fmtDate(x.createdAt)}</td><td>${esc(x.adminEmail)}</td><td>${esc(x.action)}</td><td>${esc(x.detail)}</td></tr>`).join(''))}catch(e){$('activityTable').innerHTML='<div class="empty">Activity log unavailable until Firestore rules/index are configured.</div>'}}
function loadSettings(){const raw=localStorage.getItem('ts_pan_admin_settings');if(!raw)return;try{const s=JSON.parse(raw);$('setBusiness').value=s.business||'TECH SOURCE';$('setUpi').value=s.upi||'9661905351-3@axl';$('setFee').value=s.fee||190;$('setWhatsapp').value=s.whatsapp||'9661905351'}catch{}}
$('saveSettings').onclick=()=>{localStorage.setItem('ts_pan_admin_settings',JSON.stringify({business:$('setBusiness').value,upi:$('setUpi').value,fee:$('setFee').value,whatsapp:$('setWhatsapp').value}));$('settingsMsg').textContent='Saved on this admin browser. Firebase application fee remains controlled by the application code.';toast('Settings saved')};
document.querySelectorAll('[data-section]').forEach(btn=>btn.onclick=()=>go(btn.dataset.section));document.querySelectorAll('[data-go]').forEach(btn=>btn.onclick=()=>go(btn.dataset.go));function go(id){document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('[data-section]').forEach(b=>b.classList.toggle('active',b.dataset.section===id));$('pageTitle').textContent=id==='requests'?'Payment Requests':id.charAt(0).toUpperCase()+id.slice(1);document.querySelector('.sidebar').classList.remove('open');window.scrollTo(0,0)}$('menuBtn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');

/* ================= APPROVAL + DOCUMENT CENTER UPGRADE ================= */
async function adminCloudinaryUpload(file, folder='pan_final'){
  const url='https://api.cloudinary.com/v1_1/dsnuatuc8/image/upload'; const fd=new FormData(); fd.append('file',file); fd.append('upload_preset','ml_default'); fd.append('folder',folder);
  const res=await fetch(url,{method:'POST',body:fd}); const d=await res.json(); if(!res.ok||!d.secure_url) throw new Error(d.error?.message||'Cloudinary upload failed'); return d.secure_url.replace('/upload/','/upload/f_auto,q_auto/');
}
async function adminPdfToJpg(file){
  const buf=await file.arrayBuffer(); const task=pdfjsLib.getDocument({data:buf,password:(cb)=>{const pw=prompt('Password-protected PDF: password enter karein');cb(pw||'')}}); const pdf=await task.promise; const page=await pdf.getPage(1); const vp=page.getViewport({scale:2}); const c=document.createElement('canvas'); c.width=vp.width;c.height=vp.height; await page.render({canvasContext:c.getContext('2d'),viewport:vp}).promise; const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.94)); return new File([blob],file.name.replace(/\.[^.]+$/i,'')+'.jpg',{type:'image/jpeg'});
}
function openApproveUpload(id){const a=apps.find(x=>x.id===id);if(!a)return;openModal(`<div class="approval-upload"><div class="detail-head"><div><span class="eyebrow">FINAL PAN CARD</span><h2>Approve: ${esc(a.name||'Application')}</h2><p>ACK: <b>${esc(a.ackNo)}</b></p></div></div><div class="upload-drop"><i class="fa fa-id-card" style="font-size:30px"></i><p>Final PAN card JPG upload karein. PDF bhi chalega — password PDF ko pehle JPG me convert kiya jayega.</p><input id="finalPanFile" type="file" accept="image/*,.pdf"></div><div class="upload-progress"><span id="finalPanProgress"></span></div><p id="finalPanMsg" class="message"></p><div class="detail-actions"><button onclick="closeModal()">Cancel</button><button class="success" id="finalPanApproveBtn" onclick="uploadFinalPanAndApprove('${id}')">Upload & Approve</button></div></div>`)}
async function uploadFinalPanAndApprove(id){const input=$('finalPanFile'),msg=$('finalPanMsg'),bar=$('finalPanProgress'),btn=$('finalPanApproveBtn');const file=input?.files?.[0];if(!file){msg.textContent='Final PAN card file select karein.';return}btn.disabled=true;msg.textContent='Preparing final PAN…';try{let jpg=file;if(file.type==='application/pdf'||/\.pdf$/i.test(file.name))jpg=await adminPdfToJpg(file);bar.style.width='35%';msg.textContent='Uploading final PAN…';const url=await adminCloudinaryUpload(jpg,'pan_final_cards');bar.style.width='85%';await db.collection('applications').doc(id).update({status:'approved',documentUrl:url,panCardUrl:url,finalPanCardUploadedAt:firebase.firestore.FieldValue.serverTimestamp(),statusUpdatedAt:firebase.firestore.FieldValue.serverTimestamp(),statusUpdatedBy:adminUser.email});logAction('Approved application + uploaded PAN card',apps.find(x=>x.id===id)?.ackNo||id);bar.style.width='100%';msg.style.color='#15803d';msg.textContent='Approved. PAN card ready for download.';setTimeout(closeModal,700)}catch(e){msg.style.color='#dc2626';msg.textContent=e.message||String(e);btn.disabled=false}}
window.openApproveUpload=openApproveUpload;window.uploadFinalPanAndApprove=uploadFinalPanAndApprove;

async function downloadDocJpg(url,name){try{const r=await fetch(url);const b=await r.blob();if(b.type.includes('pdf')){const f=new File([b],'doc.pdf',{type:'application/pdf'});const jpg=await adminPdfToJpg(f);const u=URL.createObjectURL(jpg);const a=document.createElement('a');a.href=u;a.download=name+'.jpg';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);return}const img=new Image();img.crossOrigin='anonymous';const u=URL.createObjectURL(b);await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=u});const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext('2d').drawImage(img,0,0);const blob=await new Promise(x=>c.toBlob(x,'image/jpeg',.94));URL.revokeObjectURL(u);const out=URL.createObjectURL(blob);const a=document.createElement('a');a.href=out;a.download=name+'.jpg';a.click();setTimeout(()=>URL.revokeObjectURL(out),1000)}catch(e){toast('JPG download failed: '+(e.message||e),'error')}}
window.downloadDocJpg=downloadDocJpg;

// Override status action so Approve always requires final PAN upload.
const _oldSetAppStatus=setAppStatus; setAppStatus=async function(id,status){if(status==='approved'){openApproveUpload(id);return}_oldSetAppStatus(id,status)};window.setAppStatus=setAppStatus;

// Enforce owner-only payment-link creation in the admin preview as well as duplicate reuse in user flow.
const _oldViewRequest=viewRequest;
viewRequest=function(id){const r=requests.find(x=>x.id===id);if(!r)return;const app=apps.find(a=>a.id===r.applicationId||a.ackNo===r.ackNo);openModal(`<div class="detail-head"><div><span class="eyebrow">Payment Request</span><h2>${esc(r.name||'Customer')}</h2><p>ACK: <b>${esc(r.ackNo)}</b></p></div>${statusBadge(r.status)}</div><div class="detail-grid">${field('Request ID',r.id)}${field('ACK',r.ackNo)}${field('Amount','₹'+Number(r.amount||190))}${field('Mobile',r.phone)}${field('Application',r.applicationType)}${field('UTR',r.utr||'—')}${field('Status',r.status||'pending')}${field('Created',fmtDate(r.createdAt))}</div><div class="detail-actions">${app?`<button class="success" onclick="verifyPayment('${app.id}',true)">Mark Paid</button><button class="danger" onclick="verifyPayment('${app.id}',false)">Reject Payment</button>`:''}<button onclick="editPaymentRequest('${r.id}')">Edit Request</button>${r.paymentScreenshot?`<button onclick="downloadDocJpg('${esc(r.paymentScreenshot)}','PAYMENT_${esc(r.ackNo)}')">Download Proof JPG</button>`:''}</div>`)};
window.viewRequest=viewRequest;
function editPaymentRequest(id){const r=requests.find(x=>x.id===id);if(!r)return;openModal(`<h2>Edit Payment Request</h2><div class="admin-edit-grid"><div><label>Amount</label><input id="editReqAmount" type="number" min="190" value="${Number(r.amount||190)}"></div><div><label>Status</label><select id="editReqStatus"><option>pending</option><option>customer_marked_paid</option><option>verification_pending</option><option>paid</option><option>rejected</option></select></div><div><label>UTR</label><input id="editReqUtr" value="${esc(r.utr||'')}"></div><div><label>UTR Mode</label><select id="editReqUtrMode"><option value="required">required</option><option value="optional">optional</option></select></div></div><div class="detail-actions"><button onclick="closeModal()">Cancel</button><button class="success" onclick="savePaymentRequestEdit('${id}')">Save</button></div>`);$('editReqStatus').value=r.status||'pending';$('editReqUtrMode').value=r.utrMode||'required'}
async function savePaymentRequestEdit(id){try{const amount=Math.max(190,Number($('editReqAmount').value||190));const status=$('editReqStatus').value;const utr=$('editReqUtr').value.trim();const mode=$('editReqUtrMode').value;const r=requests.find(x=>x.id===id);await db.collection('customerPaymentRequests').doc(id).update({amount, status,paymentStatus:status,utr,utrMode:mode,utrRequired:mode==='required',adminUpdatedAt:firebase.firestore.FieldValue.serverTimestamp(),adminUpdatedBy:adminUser.email});if(r?.applicationId)await db.collection('applications').doc(r.applicationId).update({paymentStatus:status==='paid'?'paid':status,customerPaymentAmount:amount,paymentUtr:utr});toast('Payment request updated');closeModal()}catch(e){toast(e.message,'error')}}
window.editPaymentRequest=editPaymentRequest;window.savePaymentRequestEdit=savePaymentRequestEdit;
/* ================= V3 REMARK PRESETS ================= */
const V3_REMARKS_KEY='ts_pan_remark_presets';
async function loadRemarkPresets(){try{const snap=await db.collection('remarkPresets').orderBy('createdAt','asc').get();return snap.docs.map(d=>({id:d.id,...d.data()}));}catch{return JSON.parse(localStorage.getItem(V3_REMARKS_KEY)||'[]')}}
async function saveRemarkPreset(text){text=String(text||'').trim();if(!text)return;try{await db.collection('remarkPresets').add({text,createdAt:firebase.firestore.FieldValue.serverTimestamp(),createdBy:adminUser.email});}catch{const a=JSON.parse(localStorage.getItem(V3_REMARKS_KEY)||'[]');if(!a.includes(text))a.push(text);localStorage.setItem(V3_REMARKS_KEY,JSON.stringify(a))}}
async function v3OpenRemark(id,status){const a=apps.find(x=>x.id===id);if(!a)return;const presets=await loadRemarkPresets();openModal(`<h2>Update Status & Remark</h2><div class="admin-edit-grid"><div><label>Status<select id="v3RemarkStatus"><option>pending</option><option>under process</option><option>approved</option><option>rejected</option></select></label></div><div><label>Saved Remark<select id="v3RemarkPreset"><option value="">Select saved remark</option>${presets.map(x=>`<option>${esc(x.text)}</option>`).join('')}</select></label></div></div><label>Remark<textarea id="v3RemarkText" rows="4" placeholder="Enter remark…">${esc(a.remark||'')}</textarea></label><div class="detail-actions"><button onclick="closeModal()">Cancel</button><button class="primary" onclick="v3SaveStatusRemark('${id}')">Update Status</button></div>`);$('v3RemarkStatus').value=status||a.status||'pending';$('v3RemarkPreset').onchange=()=>{if($('v3RemarkPreset').value)$('v3RemarkText').value=$('v3RemarkPreset').value};}
async function v3SaveStatusRemark(id){const status=$('v3RemarkStatus').value,remark=$('v3RemarkText').value.trim();try{if(remark)await saveRemarkPreset(remark);await db.collection('applications').doc(id).update({status,remark,statusUpdatedAt:firebase.firestore.FieldValue.serverTimestamp(),statusUpdatedBy:adminUser.email});logAction('Updated status and remark',id);toast('Status & remark updated');closeModal();loadAll();}catch(e){toast(e.message,'error')}}
window.v3OpenRemark=v3OpenRemark;window.v3SaveStatusRemark=v3SaveStatusRemark;
// Replace application action modal with a dedicated status+remark workflow.
const _v3ViewAppBase=viewApp;
viewApp=async function(id){const a=apps.find(x=>x.id===id);if(!a)return;openModal(`<div class="detail-head"><div><span class="eyebrow">${esc(a.applicationType||'New PAN')}</span><h2>${esc(a.name||'Application')}</h2><p>ACK: <b>${esc(a.ackNo)}</b> • ${fmtDate(a.createdAt)}</p></div><div>${statusBadge(a.status)} ${statusBadge(a.paymentStatus||'pending')}</div></div><div class="detail-actions"><button class="primary" onclick="v3OpenRemark('${id}','under process')">Update Status / Remark</button><button onclick="openDocs('${id}')">Documents</button><button onclick="whatsappApp('${id}')">WhatsApp</button></div><div class="detail-grid">${field('ACK Number',a.ackNo)}${field('Applicant',a.name)}${field('Mobile',a.phone)}${field('Email',a.email)}${field('PAN',a.panNumber||'—')}${field('DOB',a.dob)}${field('Gender',a.gender)}${field('Father',a.father||a.fatherName)}${field('Mother',a.mother||a.motherName)}${field('Address',[a.flatNo,a.villageCity,a.postOffice,a.subDivision,a.district,a.state,a.pinCode].filter(Boolean).join(', '))}${field('Payment Amount','₹'+Number(a.paymentAmount||190))}${field('UTR',a.paymentUtr||a.utr||'—')}${field('Remark',a.remark||'—')}</div><div class="timeline"><h3>Application Timeline</h3>${timeline(a)}</div>`)};
window.viewApp=viewApp;
